### ISSUE TITLE
deprecate or test shapely_ext

### ISSUE THREAD

**Issue by ljwolf** [pysal/libpysal#114]
the shapely extension was and is a very handy piece of code, wrapping correct interfaces between PySAL and shapely. 

It's also used by `geotable`, my shapely-less mimick of `geopandas`, and the testing suite for the `io.wkb` module. 

Currently, tests are not run for this code. Further, usually teach geopandas directly for this functionality. There is also some loss of information moving from shapely to pysal, since we do not maintain the order in which holes are nested inside exterior rings ([pysal/#820](https://github.com/pysal/pysal/issues/820), [pysal/#852](https://github.com/pysal/pysal/issues/852)).

So, we should either:
1. deprecate the shapely extension. This would not affect `geotable`, since that dependency is soft. It *would* affect tests for `wkb`, which should be simple to switch using `shapely.geometry.shape`. 
2. write tests for (and commit to maintain) this namespace.

**Comment by jGaboardi** [comment]
Is the current (ongoing) `libpysal` Travis failure related to the `shapely_ext.py` issue?

```
$ nosetests --with-doctest --verbose --with-coverage --cover-package=libpysal -I shapely_ext.py;

Doctest: libpysal.cg.alpha_shapes.alpha_geoms
... python: GeometryComponentFilter.cpp:28: virtual void geos::geom::GeometryComponentFilter::filter_rw(geos::geom::Geometry*): Assertion `0' failed.
/home/travis/.travis/job_stages: line 104:  4648 Aborted
(core dumped) nosetests --with-doctest --verbose --with-coverage --cover-package=libpysal -I shapely_ext.py
The command "nosetests --with-doctest --verbose --with-coverage --cover-package=libpysal -I shapely_ext.py;" exited with 134.

Done. Your build exited with 1.
```

**Comment by jGaboardi** [comment]
@sjsrey This can probably be closed now, correct? [`shapely_ext.py`] is [currently being tested, and is passing](https://travis-ci.org/pysal/libpysal/jobs/651718207#L2607).

**Comment by sjsrey** [comment]
Good catch.
