### ISSUE TITLE
weights.distance.KNN.from_dataframe ignoring radius 

### ISSUE THREAD

**Issue by sjsrey** [pysal/libpysal#116]
![2018-10-20-1806-1540084013-sel](https://user-images.githubusercontent.com/118042/47262075-160c8380-d493-11e8-80bb-463700554060.png)
[files.zip](https://github.com/pysal/libpysal/files/2498705/files.zip)

**Comment by ljwolf** [comment]
I remember hitting this in Riverside. I thought I fixed it in the first commit [here](https://github.com/pysal/libpysal/pull/82).

**Comment by ljwolf** [comment]
Hmm, maybe it's that, if `radius` is passed, we also need to set `distance_metric="arc"`

**Comment by sjsrey** [comment]
fixed with #117
