### ISSUE TITLE
unable to updata libpysal in Anaconda

### ISSUE THREAD

**Issue by StevenLi-DS** [pysal/libpysal#133]
I think the problem began to appear since the birth of `libpysal` and it has been months and the package still listed as `pysal` in Anaconda and cannot be updated.
![snipaste_357](https://user-images.githubusercontent.com/33796896/51915204-825b2500-23a8-11e9-8361-7934c435252b.png)

**Comment by stevencollinscn** [comment]
I did actually conda install `libpysal` but I thought `libpysal` was designed to replace `pysal` right?

**Comment by stevencollinscn** [comment]
@sjsrey Btw, are you still teaching any spatial analysis courses with Python? I found some materials from your class before, but the usage are at a very low-level even the IO. But today there is `geopandas`, I'm curious if you are writing anything that would cover some common usage of the current pysal ecosystem? I have been trying to get rid of `geoda` to make my research more reproducible.

**Comment by sjsrey** [comment]
> @sjsrey Btw, are you still teaching any spatial analysis courses with Python? I found some materials from your class before, but the usage are at a very low-level even the IO. But today there is `geopandas`, I'm curious if you are writing anything that would cover some common usage of the current pysal ecosystem? I have been trying to get rid of `geoda` to make my research more reproducible.

Yes, there is a bunch in the works - a book should be announced in the very near future. We also have been giving workshops - latest was: [NARSC 2018](https://github.com/sjsrey/pysalnarsc18). And, there is a [PySAL notebooks project](http://darribas.org/notebooks/intro.html) that we are developing.

**Comment by stevencollinscn** [comment]
@sjsrey Thanks a lot for sharing!
