### ISSUE TITLE
Some functions do not support silence_warnings=True

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#134]
Hi,

is there any particular reason why some of the functions (like `higher_order()`) do not support `silence_warnings=True`? Looking into the code it should be quite simple to add it. I am willing to do a PR, if it is not an intention to always show warnings.

**Comment by ljwolf** [comment]
Yeah, we're definitely game to handle that. I think generically, we might want to allow for `**kwargs` any time there's a weights construction underneath some function. Feel free to PR!

**Comment by jGaboardi** [comment]
#158
