### ISSUE TITLE
build_lattice_shapefile swapped arguments

### ISSUE THREAD

**Issue by renanxcortes** [pysal/libpysal#138]
I was building regular rectangular lattices in one my applications and realized that the arguments of
pysal.weights.build_lattice_shapefile is swapped as follows:

![image](https://user-images.githubusercontent.com/22593188/49619226-8d797200-f970-11e8-9799-7d033888c03c.png)

The nrows gives the number of columns and vice-versa. The reproducible code would be (in a Jupyter notebook):

```
import pysal as ps
import geopandas as gpd

%matplotlib inline
ps.weights.build_lattice_shapefile(nrows = 2, ncols = 6, outFileName = 'reg_lat.shp')
lat_2_6 = gpd.read_file('reg_lat.shp')
lat_2_6.plot(edgecolors = 'black')
```

Best,
Renan

**Comment by jGaboardi** [comment]
This appears to have already been resolved. See my this [`gist`](https://nbviewer.jupyter.org/gist/jGaboardi/993cb61df5f367f2a08cf137ae6c8a93).

**Comment by renanxcortes** [comment]
Ow, yes, you're right! Thank you for closing this!
