### ISSUE TITLE
sphinxcontrib-napoleon is no longer necessary

### ISSUE THREAD

**Issue by QuLogic** [pysal/libpysal#146]
In ca4a1ac3af389035de15786a71d5082d29eebbfe, the docs were switched to use the napoleon extension that's builtin to Sphinx 1.3+.

The current Sphinx requirement is `sphinx>=1.4.3`, so now `sphinxcontrib-napoleon` can be removed from `requirements_docs.txt`.

**Comment by QuLogic** [comment]
Oh, actually, in `conf.py`, napoleon is commented out and numpydoc is used instead, so it's definitely not needed.

**Comment by jGaboardi** [comment]
@ljwolf @sjsrey I am wondering if this may have something do with our current `doctest` failures...

#142 #145 #144

**Comment by jGaboardi** [comment]
Being addressed in [`c6361a7`](https://github.com/pysal/libpysal/pull/142/commits/c6361a74bbc13c54ca43b2c2829c77c19ffce28a) and [`0367c40`](https://github.com/pysal/libpysal/pull/142/commits/0367c40e00d6dfd37c08c93be63b7ee6d939444e)
