### ISSUE TITLE
network weights

### ISSUE THREAD

**Issue by knaaptime** [pysal/libpysal#151]
we're toying with the idea of adding a functiont to compute kernel weights on a street network using pandana

[this](https://gist.github.com/knaaptime/538584080e49dcc424568690b915cbe7) doesn't exactly walk through the process of creating those weights, but shows how you could use pandana to get your network kernel

edit: not a kernel specifically [this is a nice discussion of the problem](https://onlinelibrary.wiley.com/doi/abs/10.1111/sjos.12255)

**Comment by jGaboardi** [comment]
pysal/spaghetti#258

**Comment by sjsrey** [comment]
KDE on networks is not as straightforward as in the 2-d planar space case. The complications are outlined in section 9.2.3 of 

@book{okabe2012spatial,
  title={Spatial analysis along networks: statistical and computational methods},
  author={Okabe, Atsuyuki and Sugihara, Kokichi},
  year={2012},
  publisher={John Wiley \& Sons}
}


These should be handled before we generate kernel based weights for the network.

**Comment by knaaptime** [comment]
i think we can work on kernel issues in a separate push. It still makes sense to have network weights even if they dont satisfy all the properties of a kernel

**Comment by jGaboardi** [comment]
Note that network weights are already possible with [`spaghetti.Network.contiguityweights`](https://pysal.org/spaghetti/generated/spaghetti.Network.html#spaghetti.Network.contiguityweights) (see code [here](https://github.com/pysal/spaghetti/blob/0cc13b8a4d47795a82bfca9a20513c008392564e/spaghetti/network.py#L820)). For an example see the [Network Spatial Weights notebook](https://pysal.org/spaghetti/notebooks/network-spatial-weights.html).

**Comment by jGaboardi** [comment]
https://gist.github.com/sgillies/2217756
