### ISSUE TITLE
libpysal 4.1.0 is not released on pypi or conda-forge

### ISSUE THREAD

**Issue by weikang9009** [pysal/libpysal#169]
The most recent version of libpysal on pypi and conda-forge is v4.0.1 from Oct 2018 https://pypi.org/project/libpysal/#history

We should probably make a release on pypi for consistency (conda-forge will automatically update once there is a new release on pypi).

**Comment by ljwolf** [comment]
I definitely didn't realize 4.1.0 was released on GitHub! Nice!

I wanted to get the voronoi pr (#135) merged for a release.  Is that possible?

**Comment by QuLogic** [comment]
But it's already tagged, for 2 months now. The release is "in the wild" now.

**Comment by ljwolf** [comment]
tagged on github is not the same as released on pypi. `pip install libpysal` should still bring `v4.0.1`.

**Comment by sjsrey** [comment]
now on pypi https://pypi.org/project/libpysal/
