### ISSUE TITLE
Request a new release of libpysal

### ISSUE THREAD

**Issue by weikang9009** [pysal/libpysal#17]
libpysal relies on shapely as a dependency but does not demand the installation procedure to automatically install shapely.

libpysal [api.py](https://github.com/pysal/libpysal/blob/master/libpysal/api.py) contains a collection of functions/classes in libpysal including those dependent on shapely and those not. For users who only want to use non-shapely-dependent functions and do not install shapely on their machine, ```import libpysal.api``` would be problematic in the [current released version of libpysal](https://pypi.python.org/pypi/libpysal/3.0.0). This is also [a vital issue for giddy](https://github.com/pysal/giddy/pull/20) which uses non-shapely-dependent functions from ```import libpysal.api``` .

Fortunately [this commit](https://github.com/pysal/libpysal/commit/0b93559bec0c7e2c19e4c001d77c1ce72cb8c9ca) (*only import the shapely extension if shapely is available*) resolves this issue. Thus it would be very important to release a new version of libpysal with this commit integrated.

**Comment by ljwolf** [comment]
@weikang9009 this is resolved now, correct? The release was 2 weeks ago? Or, do we need another?

**Comment by weikang9009** [comment]
Yes. It has been resolved. Sorry that I missed the message...

**Comment by ljwolf** [comment]
no prob :) just wanted to close
