### ISSUE TITLE
Big tarball

### ISSUE THREAD

**Issue by ocefpaf** [pysal/libpysal#174]
The PyPI tarball is ~25 MB, most of is the examples folder.
If the original design is to ship that folder with the tarball please close the issue, if not I can send a PR excluding that folder from the MANIFEST to produce a smaller tarball.

**Comment by sjsrey** [comment]
There is a start of this in my [fetch](https://github.com/sjsrey/libpysal/tree/fetch) branch.

Starting with the largest example `nat` and following the logic of scikit-learn.

We probably have to refactor [examples/__init__.py](https://github.com/sjsrey/libpysal/blob/fetch/libpysal/examples/__init__.py) so `file_2_dir` can be updated after a fetch.

Was thinking anything > 1m has to go in the fetch category (and will be removed from the source distribution).

**Comment by sjsrey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fetch](https://trello.com/c/EbMY3vct/1-fetch)

**Comment by jGaboardi** [comment]
@sjsrey Do we need a trello account to access that link?

**Comment by sjsrey** [comment]
Addressed in #176
