### ISSUE TITLE
Import libpysal failed on python 3.5 and 3.6

### ISSUE THREAD

**Issue by weikang9009** [pysal/libpysal#18]
In both python 3.5 and 3.6 environments (on a mac), an attempt to import libpysal after ```pip install libpysal``` will incur the following error:
```
In [1]: import libpysal
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3a2ef2a3cd6f> in <module>()
----> 1 import libpysal

/Users/weikang/anaconda/envs/py3/lib/python3.6/site-packages/libpysal/__init__.py in <module>()
     21     Tools for creating and manipulating weights
     22 """
---> 23 import cg
     24 import io
     25 import weights

ModuleNotFoundError: No module named 'cg'
```
Import is fine in a python 2.7 environment.

**Comment by sjsrey** [comment]
This can happen if the pip used to install libpysal was python 2.7 not python 3x.

**Comment by weikang9009** [comment]
I was using the following version of pip to install libpysal:
```
(py3) Weis-Air:python_repos weikang$ pip --version
pip 9.0.1 from /Users/weikang/anaconda/envs/py3/lib/python3.6/site-packages (python 3.6)
```
This shows that the pip is python 3.6?

**Comment by sjsrey** [comment]
It could be that if you installed with 3.6 after installing with 2.7, that pip under 3.6 sees that libpysal was already installed so it just uses that rather than reinstalling it. If so then libpysal would not get converted from 2 to 3.

Under 3 here is a way to check:

```
pip uninstall libpysal
pip install --no-cache-dir libpysal
```

**Comment by weikang9009** [comment]
Thanks. The import works fine now!

**Comment by danfllash2003** [comment]
Dear friends:

For **QGIS 2.x** or **Python 2.x** you must use:
pip install pysal==1.14.3
and for **QGIS 3.x** or **Python 3.x**:
pip install pysal==2.0.0

Best regards.
