### ISSUE TITLE
WSP(sparse).to_W() has `array`s in weights,neighbors dictionaries, rather than lists. 

### ISSUE THREAD

**Issue by ljwolf** [pysal/libpysal#185]
All of the `scipy.sparse` stuff provides arrays when you call into `indices` or `indptr` or `data`. 

When we use these in [line 1454](https://github.com/pysal/libpysal/blob/e6998425b917d342ece7a569abe5df6a15af220a/libpysal/weights/weights.py#L1454), we never force them to be lists; we accept them as arrays. 

For stability and consistency, these need to be cast to lists.

**Comment by jGaboardi** [comment]
Is this only on [line 1454](https://github.com/pysal/libpysal/blob/e6998425b917d342ece7a569abe5df6a15af220a/libpysal/weights/weights.py#L1454) of `weights/weights.py` or are there other occurrences?

**Comment by ljwolf** [comment]
It's hard to catch these kinds of bugs generally, because they're all about type stability & python is very lax about types. 

But, we'll catch more in the future, and fix them when they arise... they're not super critical, since most of the inconsistencies between list & array interfaces have been ironed out above our heads, or we're not using them in ways that breed incompatibilities.
