### ISSUE TITLE
Weight Object Question

### ISSUE THREAD

**Issue by achapkowski** [pysal/libpysal#208]
I was reading the help and I was trying to figure out what some of the properties mean on the weight object.

1. What does `s0`, `s1`, `s2` mean?  I see the formula, but what do those number represent?  The doc is lacking there.  Could someone please shed some light on these properties?

**Comment by jGaboardi** [comment]
Also, the formulas aren't being rendered in the docs.

  * [pysal.lib.weights.W](https://pysal.org/pysal/generated/pysal.lib.weights.W.html#pysal.lib.weights.W)
  * [libpysal.weights.W](https://pysal.org/libpysal/generated/libpysal.weights.W.html#libpysal.weights.W)

**Comment by sjsrey** [comment]
@achapkowski thanks for raising the issue. We will be fixing the rendering of the docs and will add more information about those measures. For now they are functions of the `W` matrix that are used by a number of tests for [spatial autocorrelation](https://github.com/pysal/esda/blob/master/esda/moran.py#L192) and econometric tests/estimation methods.

**Comment by achapkowski** [comment]
@sjsrey thanks for the information, so it's a convenience property for other calculations?  

Here is some doc on math in rst files: http://svn.python.org/projects/doctools/trunk/doc/ext/math.rst

**Comment by ljwolf** [comment]
@achapkowski Yes, they're fixed quantities useful to compute standard errors for spatial autocorrelation estimators and are there for convenience. 

If you look at where they are in the code (e.g. [Moran](https://github.com/pysal/esda/blob/master/esda/moran.py#L196), [Geary](https://github.com/pysal/esda/blob/master/esda/geary.py#L164), [Getis-Ord](https://github.com/pysal/esda/blob/master/esda/getisord.py#L148)), you can see they have something to do with [analytical expressions about the variance of random variables](https://en.wikipedia.org/wiki/Variance#Definition).

**Comment by achapkowski** [comment]
@ljwolf thanks for the follow up.  


Is there some way to compare n number of weights (thinking of AIC or BIC) in pysal?  So let's say I make 100 weights matrices off of the same dataset adjusting the input parameters accordingly, say a distance parameter, how can I assume one of better over another? Is there a metric for this?  

That is why I started looking at the s0, s1, etc.. properties.

**Comment by sjsrey** [comment]
> @ljwolf thanks for the follow up.
> 
> Is there some way to compare n number of weights (thinking of AIC or BIC) in pysal? So let's say I make 100 weights matrices off of the same dataset adjusting the input parameters accordingly, say a distance parameter, how can I assume one of better over another? Is there a metric for this?
> 
> That is why I started looking at the s0, s1, etc.. properties.

@article{anselin1986non,
  title={Non-Nested Tests on the Weight Structure in Spatial Autoregressive Models: Some Monte Carlo Results},
  author={Anselin, Luc},
  journal={Journal of Regional Science},
  volume={26},
  number={2},
  pages={267--284},
  year={1986},
  publisher={Wiley Online Library}
}

@Inbook{Florax1995,
author="Florax, Raymond J. G. M.
and Rey, Serge",
editor="Anselin, Luc
and Florax, Raymond J. G. M.",
title="The Impacts of Misspecified Spatial Interaction in Linear Regression Models",
bookTitle="New Directions in Spatial Econometrics",
year="1995",
publisher="Springer Berlin Heidelberg",
address="Berlin, Heidelberg",
pages="111--135",
abstract="In most applied empirical studies in the realm of amongst others regional economics, urban planning and environmental economics, the estimation of ana priorispecified model is based on observations for a finite set of spatial units. This causes a number of persistent problems, which to varying extents have been dealt with in the literature. Essentially, the more fundamental problems boil down to the following issues.",
isbn="978-3-642-79877-1",
doi="10.1007/978-3-642-79877-1_5",
url="https://doi.org/10.1007/978-3-642-79877-1_5"
}
