### ISSUE TITLE
libpysal 4.2.0 won't import on Windows

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#214]
Hi, since the latest release libpysal will not import on windows due to encoding error. It raises `UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 503: character maps to <undefined>`. 

Details: https://ci.appveyor.com/project/martinfleis/momepy/builds/29802733

Highly likely caused by #176. I assume that adding `encoding="utf8"` to `open()` on lines 50 and 56 will fix the issue. I am unable to try that locally as I do not have windows machine until 6th of January.

**Comment by jGaboardi** [comment]
> adding encoding="utf8" to open() on lines 50 and 56 will fix the issue

@martinfleis I have tested this on a Windows machine and your solution works. I will push up a PR shortly.

**Comment by sjsrey** [comment]
Fixed with #215
