### ISSUE TITLE
duplicate pypi package badge

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#221]
The `pypi package` badge is [`README.rst`](https://github.com/pysal/libpysal/blob/master/README.rst) is duplicated.

Choices here include:
* Replacing with a badge from...
  * conda-forge/Anaconda, i.e. [![Conda Version](https://img.shields.io/conda/vn/conda-forge/libpysal.svg)](https://anaconda.org/conda-forge/libpysal)
  * pypi/conda-forge downloads, i.e. [![Downloads](https://pepy.tech/badge/libpysal)](https://pepy.tech/project/libpysal)
      * as a side note the current `pip install pysal` downloads are: [![Downloads](https://pepy.tech/badge/pysal)](https://pepy.tech/project/pysal)
  * AppVeyor/Circle CI following #219 
* Simply removing because not everyone is as big a fan of badges as I am.

**Comment by sjsrey** [comment]
Nice catch.

I'd say replacing with the conda-forge/Anaconda badge makes sense.

The pysal badge should go over to the [meta project](https://github.com/pysal/PySAL)

**Comment by jGaboardi** [comment]
addressing in #222
