### ISSUE TITLE
Handling coincident points in KNN

### ISSUE THREAD

**Issue by ljwolf** [pysal/libpysal#23]
Refer to [pysal#579](https://github.com/pysal/pysal/issues/579) and [941](https://github.com/pysal/pysal/issues/941).

**Comment by iamwfx** [comment]
+1 Just ran into this error when trying to create weights for 311 data.

**Comment by ljwolf** [comment]
for reference, `sklearn.neighbors.kneighbors_graph` solves this problem, allowing for the removal of coincident points from the neighbor identification.
