### ISSUE TITLE
Nose is unmaintained

### ISSUE THREAD

**Issue by QuLogic** [pysal/libpysal#241]
Nose is dead, and has been dead for years. Its repository hasn't seen a commit in nearly 4 years. For example, it will likely not work with Python 3.9 https://github.com/nose-devs/nose/issues/1099

Probably best to move off it to something like [pytest](https://docs.pytest.org/en/latest/). Fortunately, pytest does not really require any changes to code, but you do get some advantages if you do move, like test parameterization.

**Comment by sjsrey** [comment]
We moved to pytest with https://github.com/pysal/libpysal/commit/a5ecd27005d42f6f5a4c2c4780f8f84d655804f3
