### ISSUE TITLE
Add appveyor badge

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#248]
Add appveyor badge to `README.md` once #247 is merged.

`[![Build status](https://ci.appveyor.com/api/projects/status/9shp9tcx4qn4528h?svg=true)](https://ci.appveyor.com/project/pysal/libpysal)`

[![Build status](https://ci.appveyor.com/api/projects/status/9shp9tcx4qn4528h?svg=true)](https://ci.appveyor.com/project/pysal/libpysal)

**Comment by sjsrey** [comment]
Done with https://github.com/pysal/libpysal/commit/953a690595aab4df4df74e1044b00dbdc619c7a6
