### ISSUE TITLE
two modules “Wsets.py” and "util.py" depend on each other

### ISSUE THREAD

**Issue by weikang9009** [pysal/libpysal#26]
Function `WSP2W` is defined in [**util.py**](https://github.com/pysal/libpysal/blob/master/libpysal/weights/util.py#L783) which imports the module **Wsets.py**
However, in **Wsets.py**, [WSP2W](https://github.com/pysal/libpysal/blob/master/libpysal/weights/Wsets.py#L530]) is called in the function `w_clip` without prior declaration or import. We would encounter the following error if `outSP` is set False:

![image](https://user-images.githubusercontent.com/7359284/32810537-9ee4d9c4-c958-11e7-89af-03cdd56e8ab1.png)

Since **util.py** is dependent on **Wsets.py**, we cannot import `WSP2W` from **util.py**. Any idea how to resolve this?

**Comment by sjsrey** [comment]
Not sure why the [import](https://github.com/pysal/libpysal/blob/master/libpysal/weights/Wsets.py#L7) is commented out?
