### ISSUE TITLE
Unused code in weights.from_networkx()?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#261]
In the [`libpysal.weights.weights.from_networkx()`](https://github.com/pysal/libpysal/blob/334716d44f204d8687cdddd13cb95dd76e1d402d/libpysal/weights/weights.py#L289) class method, a weights object is returned in [line 311](https://github.com/pysal/libpysal/blob/334716d44f204d8687cdddd13cb95dd76e1d402d/libpysal/weights/weights.py#L311), but the method continues on to return another object, which would never be returned in the current implementation. Is this:
 1. a syntax error,
 2. a patch-work fix over old code, or 
 3. something else?

**Comment by ljwolf** [comment]
Yeah, that's code that should have been removed before the method merged. As you identify, it's never run, so it can be safely removed.

**Comment by jGaboardi** [comment]
+1. I am working on cleaning up the docs for `weights/weights.py` and will wrap this into it.

**Comment by ljwolf** [comment]
Thanks!

**Comment by jGaboardi** [comment]
Being addressed in #262
