### ISSUE TITLE
examples directory prevents installing with pyInstaller

### ISSUE THREAD

**Issue by bbenne10** [pysal/libpysal#263]
- Platform information: Deployment target is Windows. Dev host is macOS and Linux.
- Python version: 3.7.7
- SciPy version: Irrelevant to this report
- NumPy version: Irrelevant to this report

When importing libpysal, the examples are parsed and exported at module import time.
This means that the example files must be present in all deployments of libpysal,
which is problematic for us as we're deploying under pyInstaller on a Windows host. 

Furthermore, the usage of `__file__` means we cannot simply add the examples to our pyinstaller spec, as pyinstaller has an odd split of sourcecode files and data files and so the files will not be where you expect them to be.

My suggestion (and hope) is that you will abandon the implicit importing of examples in the name of namespace unification (or will provide a function that gathers the builtin examples explicitly when called rather than implicitly upon import. Essentially a function that does what lines 62 - 74 of builtin.py do).

OR you might consider simply rewriting the code to be much more defensive and not throwing exceptions when the files are missing. 

I understand that this is a targeted use case, but moving away from implicit filesystem reads (and import time side effects in general) I think warrants opening an issue. Until then, I believe that my organization will need to maintain an in-house forked version of libpysal which removes the examples directory entirely.

I'm happy to open a PR for the behavior above, but would like to talk about the preferred direction rather than guessing.

**Comment by bbenne10** [comment]
Upon further inspection, it looks like simply removing `from . import examples` from `libpysal/__init__.py` might be sufficient. Examples would still work (deferring to the `__init__.py` inside `libpysal.examples`) but would require an extra import e.g. `import libpysal.examples`

**Comment by sjsrey** [comment]
Thanks for raising this. Please open a PR for discussion along the lines you suggest and we will explore ways to handle the side-effects of the recent changes.
