### ISSUE TITLE
Voronoi_frames function causes jupyter notebook kernel to die

### ISSUE THREAD

**Issue by adriana-van-leeuwen** [pysal/libpysal#281]
- Platform information:
posix darwin
posix.uname_result(sysname='Darwin', nodename='AdrianaannasMBP', release='18.7.0', version='Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64', machine='x86_64')

- Python version: 
3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) 
[Clang 9.0.1 ]

- SciPy version:
1.4.1

- NumPy version:
1.18.1

-Libpysal version:
4.2.2

Hi, I have a problem calling voronoi_frames in jupyter notebook. Whenever I try to run a cell with the function, the kernel dies and restarts, regardless of how many or how little datapoints I use. Here is an example:

```python
>>>pts_sample = [(0.005308, 51.531865), (-0.261566, 51.508218), (-0.278433, 51.502137), (-0.031284, 51.355710)]; region_sample_df, pts_sample_df = voronoi_frames(pts_sample)
```

This is the popup message that I get:
The kernel appears to have died. It will restart automatically.

I don't see any error messages coming up on the terminal through which I launch jupyter notebook, it only says that the kernel has restarted. Since it only ever happens with this function, I thought maybe it has something to do with libpysal; if not, I'm sorry. I just don't know where to start to fix this. 

Thank you for your help!

**Comment by adriana-van-leeuwen** [comment]
Just wanted to add that the voronoi function itself runs fine. I tried calling pysal.lib.cg.voronoi_frames() instead, but it led to the same issue.

**Comment by ljwolf** [comment]
Uh oh, that sounds like an issue with your installation. Sometimes, the geospatial libraries (such as `shapely` and `fiona`) are installed with conflicting references to the underlying geospatial libraries (`geos` and `gdal`). This causes kernel crashes, since the underlying Python interpreter dies. 

If this is true, you should get more specific information when you run this in a standard python console... can you try that?

Further, can you please give the output of:

```python
import geopandas
geopandas. _version.get_version()
```

If that runs, can you see if this runs all the way to the plot of New York City Boroughs? 
```python
boroughs = geopandas.read_file(geopandas.datasets.get_path('nybb'))
boroughs.plot()
```

**Comment by adriana-van-leeuwen** [comment]
Thank you for the reply!

When I try to run it in a standard console I get 'Segmentation fault: 11'. 

My Geopandas version is 0.6.1. 

Trying to get the 'nybb' dataset again gives me a 'Segmentation fault: 11'. 

I had all of my geospatial libraries installed through an environment.yml file that we got at university - I've been having to fix quite a few things with it as I go along, but it's all very rough around the edges as I am very new to this. It quite very well be that it's not installed correctly; if you could somehow guide me through how to fix that I'd be really grateful!

**Comment by jGaboardi** [comment]
Are you working in a conda environment or the base conda installation? Can you post your package list? From the command line run:
```
$ conda list
```

**Comment by adriana-van-leeuwen** [comment]
I'm working in a conda environment.

This is the list:

affine                    2.3.0                      py_0  
appdirs                   1.4.3                    pypi_0    pypi
appnope                   0.1.0                    py37_0  
arrow-cpp                 0.14.1           py37h43d7656_1    conda-forge
arviz                     0.6.1                      py_0  
asn1crypto                1.3.0                    py37_0  
attrs                     19.3.0                     py_0  
aws-requests-auth         0.4.2                    pypi_0    pypi
backcall                  0.1.0                    py37_0  
basemap                   1.2.1            py37hee42265_1    conda-forge
beautifulsoup4            4.9.0            py37hc8dfbb8_0    conda-forge
bleach                    3.1.4                      py_0  
blosc                     1.17.1               h4a8c4bd_0    conda-forge
bokeh                     2.0.1            py37hc8dfbb8_0    conda-forge
boost-cpp                 1.70.0               h75728bb_2    conda-forge
boto3                     1.12.39                  pypi_0    pypi
botocore                  1.15.39                  pypi_0    pypi
branca                    0.3.1                      py_0    conda-forge
brotli                    1.0.7                h0a44026_0  
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.15.0            h1de35cc_1001  
ca-certificates           2020.1.1                      0  
cairo                     1.16.0            hec6a9b0_1003    conda-forge
cctools                   927.0.2              h5ba7a2e_4    conda-forge
certifi                   2020.4.5.1               py37_0  
cffi                      1.14.0           py37hb5b8e2f_0  
cfitsio                   3.470                h84d2f63_2    conda-forge
cftime                    1.1.1.1          py37h776bbcc_0  
chardet                   3.0.4                 py37_1003  
clang                     9.0.1           default_hf57f61e_0    conda-forge
clang_osx-64              9.0.1                h05bbb7f_0    conda-forge
clangxx                   9.0.1           default_hf57f61e_0    conda-forge
clangxx_osx-64            9.0.1                h05bbb7f_0    conda-forge
click                     7.1.1                      py_0  
click-plugins             1.1.1                      py_0  
cligj                     0.5.0                    py37_0  
cloudpickle               1.3.0                      py_0  
cmake                     3.17.0               hd28f656_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
colorcet                  2.0.2                      py_0  
compiler-rt               9.0.1                h6a512c6_3    conda-forge
compiler-rt_osx-64        9.0.1                h99342c6_3    conda-forge
contextily                1.0rc2                     py_1    conda-forge
coverage                  5.1                      pypi_0    pypi
cryptography              2.8              py37ha12b0ac_0  
curl                      7.67.0               ha441bb4_0  
cycler                    0.10.0                   py37_0  
cython                    0.29.16          py37h570ac47_0    conda-forge
cytoolz                   0.10.1           py37h1de35cc_0  
dask                      2.14.0                     py_0    conda-forge
dask-core                 2.14.0                     py_0  
dask-glm                  0.2.0                    py37_0  
dask-ml                   1.2.0                      py_0    conda-forge
datashader                0.10.0                     py_0    conda-forge
datashape                 0.5.4                    py37_1  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
deprecated                1.2.7                      py_0  
descartes                 1.1.0                      py_4  
dill                      0.3.1.1          py37hc8dfbb8_1    conda-forge
distributed               2.14.0                   py37_0  
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
double-conversion         3.1.5                haf313ee_1  
entrypoints               0.3                      py37_0  
esda                      2.2.1                    pypi_0    pypi
expat                     2.2.9                h4a8c4bd_2    conda-forge
feather-format            0.4.0                   py_1003    conda-forge
fiona                     1.8.6            py37h7eb7563_3    conda-forge
flask                     1.1.2                    pypi_0    pypi
flask-cors                3.0.8                    pypi_0    pypi
flask-json                0.3.4                    pypi_0    pypi
folium                    0.10.1                     py_0    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.9.1                hb4e5f40_0  
freexl                    1.0.5                h1de35cc_0  
fsspec                    0.7.1                      py_0  
gdal                      2.4.1            py37h39889d8_8    conda-forge
geographiclib             1.50                       py_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.6.1                      py_0  
geopy                     1.21.0                     py_0    conda-forge
georasters                0.5.15                   pypi_0    pypi
geos                      3.7.2                h6de7cb9_2    conda-forge
geotiff                   1.4.3             h113155d_1001    conda-forge
gettext                   0.19.8.1             h15daf44_3  
gflags                    2.2.2                h0a44026_0  
giddy                     2.3.0                    pypi_0    pypi
giflib                    5.1.7                h01d97ff_1    conda-forge
git                       2.26.0          pl526h561ab23_0    conda-forge
gitdb                     4.0.2                      py_0  
gitdb2                    4.0.2                      py_0    conda-forge
gitpython                 3.1.0                      py_0    conda-forge
glib                      2.63.1               hd977a24_0  
glog                      0.4.0                h0a44026_0  
googlemaps                4.2.0                    pypi_0    pypi
grpc-cpp                  1.25.0               h5002bfe_0    conda-forge
h5py                      2.10.0          nompi_py37h106b333_102    conda-forge
hdbscan                   0.8.26           py37h10e2902_0    conda-forge
hdf4                      4.2.13               h39711bb_2  
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
heapdict                  1.0.1                      py_0  
holoviews                 1.13.2                     py_0  
hvplot                    0.5.2                      py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.9                        py_1  
imageio                   2.8.0                      py_0  
importlib_metadata        1.5.0                    py37_0  
inequality                1.0.0                    pypi_0    pypi
intel-openmp              2019.4                      233  
ipykernel                 5.1.4            py37h39e3cac_0  
ipyleaflet                0.12.3                     py_1    conda-forge
ipyparallel               6.2.4            py37hc8dfbb8_0    conda-forge
ipython                   7.13.0           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0    conda-forge
itsdangerous              1.1.0                    pypi_0    pypi
jedi                      0.16.0                   py37_1  
jinja2                    2.11.1                     py_0  
jmespath                  0.9.5                    pypi_0    pypi
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1               h3efe00b_0  
json5                     0.9.4                      py_0  
jsonlines                 1.2.0                    pypi_0    pypi
jsonschema                3.2.0                    py37_0  
jupyter_client            6.1.2                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                1.1.4                      py_0    conda-forge
jupyterlab_server         1.1.0                      py_0  
kealib                    1.4.13               h2324030_0    conda-forge
kiwisolver                1.1.0            py37h0a44026_0  
krb5                      1.16.4               hddcf347_0  
ld64                      450.3                h3c32e8a_4    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcurl                   7.67.0               h051b688_0  
libcxx                    9.0.1                         1    conda-forge
libdap4                   3.20.4               habf5908_0    conda-forge
libedit                   3.1.20181209         hb402a30_0  
libevent                  2.1.10               hafa8578_0    conda-forge
libffi                    3.2.1                h475c297_4  
libgdal                   2.4.1                h75d216d_8    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15                 hdd342a3_7  
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm9                  9.0.1                ha1b3eb9_0    conda-forge
libnetcdf                 4.6.2             h1a02027_1003    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
libpng                    1.6.37               ha441bb4_0  
libpq                     11.5                 h31a01ba_2    conda-forge
libprotobuf               3.8.0                hd9629dc_0  
libpysal                  4.2.2                      py_0    conda-forge
libsodium                 1.0.16               h3efe00b_0  
libspatialindex           1.9.3                h0a44026_0  
libspatialite             4.3.0a            hb3e03d6_1030    conda-forge
libssh2                   1.9.0                ha12b0ac_1  
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libuv                     1.34.0               h0b31af3_0    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               9.0.1                h28b9765_2    conda-forge
llvmlite                  0.31.0           py37h1341992_0  
locket                    0.2.0                    py37_1  
lxml                      4.5.0            py37heb1707f_1    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
mapclassify               2.2.0                      py_0    conda-forge
markdown                  3.1.1                    py37_0  
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.1.3                    py37_0  
matplotlib-base           3.1.3            py37h9aa3819_0  
mercantile                1.1.2                      py_0    conda-forge
mgwr                      2.1.1                    pypi_0    pypi
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37h0b31af3_0    conda-forge
mock                      4.0.1                      py_1  
mplleaflet                0.0.5                      py_4    conda-forge
mpmath                    1.1.0                    pypi_0    pypi
msgpack-python            1.0.0            py37h04f5b5a_1  
multicoretsne             0.1                      pypi_0    pypi
multipledispatch          0.6.0                    py37_0  
munch                     2.5.0                      py_0  
mysql-connector-c         6.1.11               hccea1a4_1  
mysql-connector-python    8.0.18           py37he91358f_0    conda-forge
nbconvert                 5.6.1                    py37_0  
nbdime                    2.0.0            py37hc8dfbb8_0    conda-forge
nbformat                  5.0.4                      py_0  
ncurses                   6.1                  h0a44026_1  
netcdf4                   1.5.1.2          py37h876e625_1    conda-forge
networkx                  2.4                        py_1    conda-forge
nodejs                    13.10.1              h38d8c5a_0    conda-forge
notebook                  6.0.3                    py37_0  
numba                     0.48.0           py37h6c726b0_0  
numexpr                   2.7.1            py37h94625e5_1    conda-forge
numpy                     1.18.1           py37h7687784_1    conda-forge
olefile                   0.46                     py37_0  
openjpeg                  2.3.1                hdc36067_1    conda-forge
openssl                   1.1.1f               h1de35cc_0  
osmnet                    0.1.5                      py_3    conda-forge
osmnx                     0.11.4                     py_1    conda-forge
packaging                 20.3                       py_0  
palettable                3.3.0                      py_0    conda-forge
pandana                   0.4.4            py37h4f17bb1_1    conda-forge
pandas                    1.0.3            py37h6c726b0_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
panel                     0.9.3                      py_0  
param                     1.9.3                      py_0  
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.6.2                      py_0  
partd                     1.1.0                      py_0  
patsy                     0.5.1                    py37_0  
pcre                      8.44                 h4a8c4bd_0    conda-forge
perl                      5.26.2               h4e221da_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.2.1            py37hb6f49c9_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0               h1de35cc_0  
pointpats                 2.1.0                      py_1  
polyline                  1.4.0                      py_0    conda-forge
poppler                   0.67.0               h16886b5_8    conda-forge
poppler-data              0.4.9                         0  
postgresql                11.5                 h26bc10f_2    conda-forge
proj4                     5.2.0             h6de7cb9_1006    conda-forge
prometheus_client         0.7.1                      py_0  
prompt-toolkit            3.0.4                      py_0  
prompt_toolkit            3.0.4                         0  
protobuf                  3.8.0            py37h0a44026_0  
psutil                    5.7.0            py37h1de35cc_0  
ptyprocess                0.6.0                    py37_0  
pyarrow                   0.14.1           py37he1943e6_2    conda-forge
pycparser                 2.20                       py_0  
pyct                      0.4.6                    py37_0  
pygments                  2.6.1                      py_0  
pykrige                   1.5.0            py37h9bfed18_0    conda-forge
pymc3                     3.8                        py_0    conda-forge
pyopenssl                 19.1.0                   py37_0  
pyparsing                 2.4.6                      py_0  
pyproj                    2.4.0                    pypi_0    pypi
pyrsistent                0.16.0           py37h1de35cc_0  
pysal                     2.2.0                    pypi_0    pypi
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.1                    py37_0  
pystan                    2.19.1.1         py37h4f17bb1_1    conda-forge
pytables                  3.6.1            py37h6f8395a_1    conda-forge
python                    3.7.6           h90870a6_5_cpython    conda-forge
python-dateutil           2.8.0                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0  
pyviz_comms               0.7.4                      py_0  
pywavelets                1.1.1            py37h1de35cc_0  
pyyaml                    5.3.1            py37h1de35cc_0  
pyzmq                     18.1.1           py37h0a44026_0  
qgrid                     1.1.1                 py37_1001    conda-forge
quantecon                 0.4.6                    pypi_0    pypi
quilt3                    3.1.8                    pypi_0    pypi
rasterio                  1.0.25           py37h238e834_0    conda-forge
rasterstats               0.14.0                     py_0    conda-forge
re2                       2019.08.01           h0a44026_0  
readline                  8.0                  h1de35cc_0  
requests                  2.23.0             pyh8c360ce_2    conda-forge
requests-futures          1.0.0                    pypi_0    pypi
rhash                     1.3.8                ha12b0ac_0  
rtree                     0.9.3                    py37_0  
ruamel-yaml               0.16.10                  pypi_0    pypi
ruamel-yaml-clib          0.2.0                    pypi_0    pypi
s3transfer                0.3.3                    pypi_0    pypi
scikit-image              0.16.2           py37h4f17bb1_0    conda-forge
scikit-learn              0.22.2.post1     py37h3dc85bc_0    conda-forge
scipy                     1.4.1            py37hce1b9e5_2    conda-forge
seaborn                   0.10.0                     py_1    conda-forge
segregation               1.2.0                    pypi_0    pypi
send2trash                1.5.0                    py37_0  
setuptools                46.1.3                   py37_0  
shapely                   1.7.0                    pypi_0    pypi
simplejson                3.17.0           py37h0b31af3_0    conda-forge
six                       1.14.0                   py37_0  
smmap                     3.0.1                      py_0  
smmap2                    3.0.1                      py_0    conda-forge
smopy                     0.0.7                    pypi_0    pypi
snappy                    1.1.7                he62c110_3  
snuggs                    1.4.7                      py_0  
sompy                     1.1                      pypi_0    pypi
sortedcontainers          2.1.0                    py37_0  
soupsieve                 1.9.4            py37hc8dfbb8_1    conda-forge
spaghetti                 1.4.2.post2              pypi_0    pypi
spglm                     1.0.7                    pypi_0    pypi
spint                     1.0.6                    pypi_0    pypi
splot                     1.1.3                    pypi_0    pypi
spreg                     1.1.1                    pypi_0    pypi
spvcm                     0.3.0                    pypi_0    pypi
sqlalchemy                1.3.15           py37h9bfed18_1    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
statsmodels               0.11.1           py37h9bfed18_1    conda-forge
sympy                     1.5.1                    pypi_0    pypi
tapi                      1000.10.8            ha1b3eb9_4    conda-forge
tbb                       2020.0               h04f5b5a_0  
tblib                     1.6.0                      py_0  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
theano                    1.0.4            py37h04f5b5a_0  
thrift-cpp                0.12.0            h874095a_1004    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
tobler                    0.2.2                    pypi_0    pypi
toolz                     0.10.0                     py_0  
tornado                   6.0.4            py37h1de35cc_1  
tqdm                      4.44.1                     py_0  
traitlets                 4.3.3                    py37_0  
traittypes                0.2.1                      py_1    conda-forge
typing_extensions         3.7.4.1                  py37_0  
tzcode                    2019a             h01d97ff_1002    conda-forge
tzlocal                   2.0.0                      py_0    conda-forge
urbanaccess               0.2.0                      py_1    conda-forge
uriparser                 0.9.3                h0a44026_1  
urllib3                   1.24.3                   pypi_0    pypi
vincent                   0.4.4                      py_1    conda-forge
watermark                 2.0.2                    pypi_0    pypi
wcwidth                   0.1.9                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.12.1           py37h1de35cc_1  
xarray                    0.15.1                     py_0  
xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.2.8                      py_0    conda-forge
xz                        5.2.5                h1de35cc_0  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.3.1                h0a44026_3  
zict                      2.0.0                      py_0  
zipp                      2.2.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.4.0                ha9f0a20_0    conda-forge

**Comment by jGaboardi** [comment]
There does seem to be a mix of `conda-forge` and `pypi` installs. A specific troublemaker is probably `shapely 1.7.0 pypi_0 pypi`. The first step in debugging would be to try a fresh `conda` environment. Geopandas provides a [nice setup](https://geopandas.org/install.html) for this:

```
$ conda create -n geo_env
$ conda activate geo_env
$ conda config --env --add channels conda-forge
$ conda config --env --set channel_priority strict
$ conda install python=3 geopandas
```

From there, install other packages you need and try to run your lines of code again.

**Comment by adriana-van-leeuwen** [comment]
Thank you both so much for your help and patience! I must've broken my environment with pip installs myself when I was trying to fix an issue a few weeks ago and I didn't understand what I was doing. I removed the environment, reinstalled it using the yml file we got, fixed my previous issue without pip install, and everything works now. Nobody has explained to me the difference between pip and conda/conda forge to me before, so thank you for that too!

**Comment by jGaboardi** [comment]
No problem! It is always good for us to have a refresher, too, and providing an explanation/demonstration is excellent for that. As one basic rule of thumb (and of course there are many caveats) is that if there is a `conda-forge` version of the package you need, it is probably best to use it rather than the `pip` version.

**Comment by jGaboardi** [comment]
Resolved through rebuilt environment.
