### ISSUE TITLE
higher_order weights of <= k

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#313]
Would it be of interest to have an option in `higher_order` and consequently `higher_order_sp`, which returns not only contiguity weights of order `k`, but also of order `<=k`? `higher_order_sp(w, shortest_path=False)` is close, but misses some features which are accessible on `k-n` but not `k`.

Implementation-wise it would be trivial, just using the following:

```python
wk = sum(map(lambda x: w ** x, range(2, k + 1)))
```

instead of this, in that case, and setting `shortest_path` to `False`:
https://github.com/pysal/libpysal/blob/10c4089b05f418b11ffdb36321d2455afa3b60fa/libpysal/weights/util.py#L499

In `momepy` I have a function simulating this as

```py
joined = first_order
for i in list(range(2, k + 1)):
    i_order = libpysal.weights.higher_order(first_order, k=i)
    joined = libpysal.weights.w_union(joined, i_order)
```

but the `map` approach above is of an order of magnitude faster.

I can make a PR if there's interest.

**Comment by sjsrey** [comment]
Linking to #293 as I think there are some synergies here.

**Comment by sjsrey** [comment]
Having the option to support both the "pure" higher order neighbor weights (that do not include lower order contiguities), and the "encompassing" higher order weights (that do include the lower order contiguities) would be a good thing, as different analytical methods make use of these different cases.

Mirroring the treatment in [GeoDa](https://geodacenter.github.io/workbook/4a_contig_weights/lab4a.html#higher-order-contiguity) would be a good idea (imo).
