### ISSUE TITLE
libpysal fails to import

### ISSUE THREAD

**Issue by zoj613** [pysal/libpysal#323]
Anytime I try to import libpysal I get the error: `AttributeError: 'NoneType' object has no attribute 'find_all'`

Here is the stacktrace:
```
>>> import libpysal
/home/.pyenv/versions/occu/lib/python3.6/site-packages/libpysal/weights/util.py:20: UserWarning: geopandas not available. Some functionality will be disabled.
  warn('geopandas not available. Some functionality will be disabled.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.pyenv/versions/occu/lib/python3.6/site-packages/libpysal/__init__.py", line 30, in <module>
    from . import examples
  File "/home/.pyenv/versions/occu/lib/python3.6/site-packages/libpysal/examples/__init__.py", line 6, in <module>
    from .remotes import datasets as remote_datasets
  File "/home/.pyenv/versions/occu/lib/python3.6/site-packages/libpysal/examples/remotes.py", line 99, in <module>
    datasets = poll_remotes()
  File "/home/.pyenv/versions/occu/lib/python3.6/site-packages/libpysal/examples/remotes.py", line 30, in poll_remotes
    rows = samples.find_all("tr")
AttributeError: 'NoneType' object has no attribute 'find_all'

```
 This happened in  version `4.2.2` and is the same after upgrading to version `4.3.0`. Note that this error goes away when I downgrade scipy to version 1.2.1.

- Platform information:
```
posix linux
posix.uname_result(sysname='Linux',, release='5.4.44-1-MANJARO', version='#1 SMP PREEMPT Wed Jun 3 14:48:07 UTC 2020', machine='x86_64')
```
- Python version: 
```
3.6.10 (default, May 29 2020, 15:31:17) 
[GCC 9.3.0]
```
- SciPy version: `1.3.3`

- NumPy version: `1.19.0`

**Comment by sjsrey** [comment]
Thanks for reporting this.

I'm not able to reproduce locally:
```
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libpysal
/home/serge/anaconda3/envs/lib323/lib/python3.6/site-packages/libpysal/weights/util.py:20: UserWarning: geopandas not available. Some functionality will be disabled.
  warn('geopandas not available. Some functionality will be disabled.')
>>> libpysal.__version__
'4.3.0'
>>> import scipy
>>> scipy.__version__
'1.5.0'
>>> 
```

Is this something that just started?

**Comment by zoj613** [comment]
> Thanks for reporting this.
> 
> I'm not able to reproduce locally:
> 
> ```
> Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import libpysal
> /home/serge/anaconda3/envs/lib323/lib/python3.6/site-packages/libpysal/weights/util.py:20: UserWarning: geopandas not available. Some functionality will be disabled.
>   warn('geopandas not available. Some functionality will be disabled.')
> >>> libpysal.__version__
> '4.3.0'
> >>> import scipy
> >>> scipy.__version__
> '1.5.0'
> >>> 
> ```
> 
> Is this something that just started?

Yes, it randomly happened today. After I downgraded to scipy 1.2.1 the error went away. Then I upgraded to 1.3.1 again. The error suddenly disappeared. Not sure why it occured in the first place but changing the scipy version is what seems to have fixed it. Not sure if I should close the issue?

**Comment by sjsrey** [comment]
Thanks for confirming. Glad it is sorted. I'll close.
