### ISSUE TITLE
README.md?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#330]
Should the `README.rst` be swapped out for a `README.md`?

**Comment by jGaboardi** [comment]
Looking back at this. Is there a reason to keep the `README` as an `.rst` file? If we follow #594, then we should probably standardize to a `.md`.

cc @knaaptime @martinfleis @sjsrey

**Comment by martinfleis** [comment]
It should be `md` in my opinion. I don't think our tooling cares but markdown should always be preferred unless we need some specific RST stuff.
