### ISSUE TITLE
Rook contiguity weights fails when polygons border at two points

### ISSUE THREAD

**Issue by ischmidt20** [pysal/libpysal#333]
**Is your feature request related to a problem? Please describe.**
When I use Rook contiguity weights, pysal considers two polygons to border if the polygons border at two (or more) distinct points, even if they don't share a border.

See here: https://imgur.com/kYRqYXp

In this scenario, pysal gives a weight of 1 between polygons A and B, even their boundaries coincide at only two points, and the line between those two points is a border with a different polygon.

**Describe the solution you'd like**
I think that in this scenario, Rook contiguity should NOT treat these as equal.

**Describe alternatives you've considered**
Right now I can filter out these cases by looking at the type of the intersection of the polygon's exteriors in shapely, but this adds another step which should be avoided from the beginning. Basically if the intersection of two polygon's boundaries is a collection of points, as opposed to a line, then Rook shouldn't consider them as neighbors.

**Comment by sjsrey** [comment]
@ischmidt20 might you be able to share the source files so we can investigate further?

**Comment by ischmidt20** [comment]
Certainly! I am using US Census block shapefiles here:

https://www2.census.gov/geo/tiger/TIGER2010BLKPOPHU/tabblock2010_10_pophu.zip

It looks like the polygons in question are FID 4203 and 592. I came across this issue when working with this data on shapely, as the intersection of the two polygon exteriors was a collection of points, not a linestring or multilinestring as I would expect with rook weights.

**Comment by sjsrey** [comment]
Those two blocks are queen but not rook neighbors, so this is definitely a bug:

![Screenshot from 2020-08-09 14-30-24](https://user-images.githubusercontent.com/118042/89742252-12bdff80-da4d-11ea-98ba-0499c9218a00.png)
![Screenshot from 2020-08-09 14-30-34](https://user-images.githubusercontent.com/118042/89742253-12bdff80-da4d-11ea-839e-f7f2865d104c.png)

**Comment by ischmidt20** [comment]
Huh. I've just been re-running the cells in my notebook and it looks like these two polygons no longer border each other. It's odd, because I remember the first time I ran the code, no error showed up either, but then it showed up the second time. Maybe it has something to do with the weird way Python handles floats? Whatever it is, it seems to have been resolved on my end. Very odd, can't explain it.

**Comment by sjsrey** [comment]
Interesting. I just worked up a small example to check if this was a bug in our logic:

![image](https://user-images.githubusercontent.com/118042/89742715-308d6380-da51-11ea-90ae-c711fadc229d.png)


and the rook and queen cases are handled correctly here.
