### ISSUE TITLE
rename `master` branch to `main` branch

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#353]
See also pysal/spopt#68

#### 1. Renaming the organization remote `master` branch.
1. Create a renamed copy of the `master` branch.
  * ```
     $ git branch -m master main
      ```
2. Push the renamed copy to ***the organization*** remote.
  * ```
     $ git push -u upstream main
     ```
3. Update the [`default`](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/changing-the-default-branch) branch in `Settings/Branches`.
4.  Delete ***the organization*** remote `master`.
  * ```
     $ git push upstream --delete master
     ```

-------------
#### 2. Renaming your remote `master` branch.
1. Create a renamed copy of the `master` branch.
  * ```
     $ git branch -m master main
      ```
2. Push the renamed copy to ***your*** remote.
  * ```
     $ git push -u origin main
     ```
3. Update the [`default`](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/changing-the-default-branch) branch in `Settings/Branches`.
4.  Delete ***your*** remote `master`.
  * ```
     $ git push origin --delete master
     ```

**Comment by jGaboardi** [comment]
@sjsrey I can get started on this if you like, though I will need admin permissions. Following the actual renaming we should...
* add a (temporary) note to `README.md` for devs so that they know how to set up and push to main.
* update the default branch on `codecov`.
* update links in `README.md` (badges, etc.)
* update the [Development Guides](https://github.com/pysal/pysal/wiki#development-guides) (this should be done anyway)

**Comment by martinfleis** [comment]
This is becoming easier now https://github.blog/changelog/2021-01-19-support-for-renaming-an-existing-branch/

**Comment by jGaboardi** [comment]
@martinfleis nice find

**Comment by jGaboardi** [comment]
pysal/giddy#174, pysal/inequality#20, pysal/mapclassify#130, pysal/spreg#106

**Comment by jGaboardi** [comment]
Just tried out the "new" automated way in `esda` that @martinfleis pointed out earlier. Super easy to simply rename the `master` branch to `main`, which automatically updates+redirects open PRs. @sjsrey if you give the green light/thumbs up for this I can go ahead and pull the trigger.

**Comment by martinfleis** [comment]
For the other packages that have not been transitioned to main yet, please use the automated way linked above.
