### ISSUE TITLE
`examples.explain` returning 404

### ISSUE THREAD

**Issue by darribas** [pysal/libpysal#364]
I've had several reports of this behaviour (including my own) on `pysal2.3.0`/`libpysal4.3.0`:

![Screenshot from 2020-11-23 10-33-27](https://user-images.githubusercontent.com/417363/99952500-aa82f780-2d77-11eb-88f5-80692c524268.png)

I'd imagine this has to do with a change in the API upstream at the @GeoDaCenter? Just guessing, might be something else.

**Comment by sjsrey** [comment]
Thanks for reporting. My guess is something moved. WIll investigate.

**Comment by martinfleis** [comment]
Closed by #368
