### ISSUE TITLE
refactor examples

### ISSUE THREAD

**Issue by knaaptime** [pysal/libpysal#369]
we've had some recent issues where filenames from some remote datasets were changed, unknowingly breaking access to some data. We want to restructure the examples a bit as following:

1. borrow design ideas (and possibly hook into) [pooch](https://github.com/fatiando/pooch) and [intake](https://intake.readthedocs.io/en/latest/)
2. define datasets as a collection of YAML files (so users can also contribute datasets by simply defining the appropriate fields in a yaml
3. parse the geoda site using current machinery and build those yamls on the fly
4. include CI tests that examine whether remote datasets can be accessed (and optionally check for cols/rows)
5. Fix pandas rendering of available datasets

**Comment by knaaptime** [comment]
a few of the links on geoda's [datasets page](https://geodacenter.github.io/data-and-lab/) aren't always as advertised (e.g. "cars.zip" is really "Abandoned_Vehicles_Map.csv" and "CHIM.zip" is really a box.com [link](https://uchicago.box.com/s/yqc97nq23hoeeqo5lkc2grlg98skokgk), though most of them are accurate

**Comment by sjsrey** [comment]
I have a start at the cataloging of the remotes with yml files to allow for users to easily add new remote examples. Working on the [branch catalog](https://github.com/sjsrey/libpysal/tree/catalog).

**Comment by knaaptime** [comment]
most of this is handled by the geodatasets package
