### ISSUE TITLE
pygeos-based contiguity

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#375]
Contiguity weights (`Queen` and `Rook`) can be significantly faster if using pygeos to extract coordinates. Note that this is not a drop-in replacement of the current function since that can handle shapely and PySAL geometries (I've never worked with those). But it is good to keep this option in mind.

I also think that some of those loops can be done in Numpy or Numba to get it even more performant. However, I initially wanted to figure out how to ease memory demands, but did not succeed on that yet.

This is based on code in here: https://github.com/pysal/libpysal/blob/bc37eb438b17270c3e222941950450e93ff433ed/libpysal/weights/_contW_lists.py#L61

```py
import numpy as np
import pygeos
import geopandas as gpd
from shapely.geometry import Point
import libpysal
import collections

# create geoms in a grid 200x200
size = 200
grid = gpd.points_from_xy(
    np.repeat(np.linspace(1, size, size), size), np.tile(np.linspace(1, size, size), size)
).buffer(0.5, cap_style=3)

# these two lines do the trick, the rest is essentially copy&paste
coords = pygeos.get_coordinates(grid.data)
ints = np.repeat(np.array(range(len(grid))), pygeos.get_num_coordinates(grid.data))

items = collections.defaultdict(set)
for i, vertex in enumerate(coords):
    items[tuple(vertex)].add(ints[i])

shared_vertices = []
for item, location in list(items.items()):
    if len(location) > 1:
        shared_vertices.append(location)

w = {}
for i in range(len(grid)):
    w[i] = set()

for vert_set in shared_vertices:
    for v in vert_set:
        w[v] = w[v] | vert_set
        try:
            w[v].remove(v)
        except:
            pass
```

Timing: 
20x20 grid
current `Wall time: 68.2 ms`
new `Wall time: 5.85 ms`

200x200 grid 
current `Wall time: 2.25 s`
new `Wall time: 676 ms`

200x200 grid of circles (dense geometry)
current `Wall time: 16 s`
new `Wall time: 13.9 s`

**Comment by ljwolf** [comment]
That'd be a great contribution! 

I pieced together our current `_get_boundary_points` to allow for ducktyping of pysal polygons and shapely polygons as part of our migration to being able to work with `shapely`/`geopandas` without explicit type conversions. The original design direction was that we needed to support the pysal polygons alongside shapely polygons, and ensure the functions worked without shapely. 

Does it make sense for us to build directly on pygeos? or, should we wait for this to land in a shapely release still?

**Comment by martinfleis** [comment]
> Does it make sense for us to build directly on pygeos? or, should we wait for this to land in a shapely release still?

If we build a logic around it to make sure we can process shapely geoms (that can be taken from geopandas), `pygeos` is stable enough to be relied upon. But in the near future, it will require a change accommodating shapely 2.0.

I don't know when shapely 2.0 should come out though. If within next 6 months, then I would wait. If it'll take another year, then it is worth using pygeos now.

**Comment by ljwolf** [comment]
OK, we [use it here already](https://github.com/pysal/libpysal/blob/master/libpysal/cg/alpha_shapes.py#L513) cause we needed it for the speed. I am extremely for writing new, clean, and concise versions of these methods based on pygeos, and could sprint with folks to get it done!

**Comment by martinfleis** [comment]
Since there's an ongoing discussion on refactoring weights based on sparse array, it might make sense to wait with the new version of constructors. But in the past days I've multiple times reached limits of current weights implementation (on large DataFrames) so I am all in for some rewriting.

**Comment by jGaboardi** [comment]
xref https://github.com/pysal/libpysal/pull/482

**Comment by knaaptime** [comment]
resolved by Graph
