### ISSUE TITLE
Bump PYPI version to 4.3.1

### ISSUE THREAD

**Issue by PumpkinCheshire** [pysal/libpysal#376]
The [pypi package](https://pypi.org/project/libpysal/) has not been updated to 4.3.1. Please update.

**Comment by jGaboardi** [comment]
@knaaptime @sjsrey Shall I run the release action for this or is there a reason why we didn't publish the `v4.3.1` release to PyPI?

**Comment by sjsrey** [comment]
I think we did not have the action dialed in when we did 4.3.1. Go ahead and try it, we need to fix it if it isn't already good to go.

**Comment by jGaboardi** [comment]
> I think we did not have the action dialed in when we did 4.3.1. Go ahead and try it, we need to fix it if it isn't already good to go.

OK. In order to use the release action we'll need to bump the release to `v4.3.2` the run the action. I'll go ahead and put in a PR for that now.

**Comment by jGaboardi** [comment]
Before I try to the release action, can you (@sjsrey) confirm that we have a `PYPI_PASSWORD` token (lowercase is OK) in *Settings/Secrets* (repository secret)? I don't have the permissions to see that tab.

**Comment by sjsrey** [comment]
@jGaboardi you have permissions now.

**Comment by jGaboardi** [comment]
@sjsrey Thanks. I just checked and we don't yet have a `PYPI_PASSWORD` token for the repo. In order for me to generate this I'll also need owner status on [PyPI](https://pypi.org/project/libpysal/). If you are not comfortable granting me this permission you can generate the token following [these instructions](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github).

**Comment by sjsrey** [comment]
what is your pypi id?

**Comment by jGaboardi** [comment]
jGaboardi

**Comment by sjsrey** [comment]
Yah, that isn't working as an id on pypi for me. I went ahead and did the token so see if that works onw

**Comment by jGaboardi** [comment]
> Yah, that isn't working as an id on pypi for me. I went ahead and did the token so see if that works now.

this is odd...

**Comment by sjsrey** [comment]
just got you on there. something must have been off in what I tried for the id. you should be an owner now

**Comment by jGaboardi** [comment]
@PumpkinCheshire The latest version of `libpysal` (`v4.3.5`) is up on [PyPI](https://pypi.org/project/libpysal/).
