### ISSUE TITLE
Raster weights `w2da` failing on 3.6

### ISSUE THREAD

**Issue by sjsrey** [pysal/libpysal#399]
https://github.com/pysal/libpysal/runs/2319092171?check_suite_focus=true#step:10:698

It looks like the rows of the data attribute returned in `w2da` are inverted:
```
In [26]: da2.data
Out[26]: 
array([[[226, 229,  29, 129],
        [164, 169, 254, 126],
        [101,  34,  29,   1],
        [118, 113,  59, 142]]])

In [27]: da21.data
Out[27]: 
array([[[118, 113,  59, 142],
        [101,  34,  29,   1],
        [164, 169, 254, 126],
        [226, 229,  29, 129]]])

```

 Someone who worked on the raster gsoc might have an efficient fix?

Note, this also fails locally on python 3.7 under linux.

**Comment by sjsrey** [comment]
See #391

**Comment by darribas** [comment]
cc'ing @MgeeeeK too as he was the closest pair of eyes to the work

**Comment by MgeeeeK** [comment]
Looking into it
