### ISSUE TITLE
Dimension issues in DistanceBand weights

### ISSUE THREAD

**Issue by iboates** [pysal/libpysal#401]
- Platform information:
```
posix linux
posix.uname_result(sysname='Linux', nodename='eif-pg-12-03', release='5.4.0-65-generic', version='#73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021', machine='x86_64')
```
- Python version: 
```
3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0]
```
- SciPy version:
```
1.6.2
```
- NumPy version:
```
1.20.2
```

I am trying to calculate a weights matrix from a geodataframe and I get this error. I don't know what it means, as far as I can tell, my geodataframe is valid and compliant.

Here is the full stacktrace:

```
Traceback (most recent call last):
  File "/data/eifer.kit.edu/boates/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/data/eifer.kit.edu/boates/perf-agri-pv/venv/lib/python3.8/site-packages/libpysal/weights/distance.py", line 606, in from_dataframe
    pts = get_points_array(df[geom_col])
  File "/data/eifer.kit.edu/boates/perf-agri-pv/venv/lib/python3.8/site-packages/libpysal/weights/util.py", line 1075, in get_points_array
    data = np.vstack([shape for shape in backup])
  File "<__array_function__ internals>", line 5, in vstack
  File "/data/eifer.kit.edu/boates/perf-agri-pv/venv/lib/python3.8/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1001 has size 1
```

I'm calling it like this:

```
import json
import geopandas as gpd
import libpysal as lps

readings_json = json.load("pysal_error_data.txt")
readings_gdf = gpd.GeoDataFrame.from_features(readings_json["features"])

weights = lps.weights.DistanceBand.from_dataframe(readings_gdf, threshold=50000)
```

JSON data: [pysal_error_data.txt](https://github.com/pysal/libpysal/files/6304526/pysal_error_data.txt)

**Comment by ljwolf** [comment]
The last part of the traceback is `lps.weights.DistanceBand.from_dataframe: ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1001 has size 1`. Could you post the full error? Copy it all, entirely?

**Comment by iboates** [comment]
> 
> 
> The last part of the traceback is `lps.weights.DistanceBand.from_dataframe: ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1001 has size 1`. Could you post the full error? Copy it all, entirely?

I just updated the original question with the full stacktrace.

**Comment by ljwolf** [comment]
Wonderful, thank you! 

This happens on any weights:

```python
import geopandas
from libpysal import weights

gdf = geopandas.read_file("./pysal_error_data.txt")
weights.DistanceBand.from_dataframe(gdf, threshold=50_000) # errors
weights.KNN.from_dataframe(gdf) # same error
```

Looking a little bit harder, I see you have features with "null" geometries 
```python
gdf.geometry.isnull().any()
```

So, if you remove these:
```python
nonnull = gdf[~gdf.geometry.isnull()]
```

Then you can compute the weights:
```python
w = weights.DistanceBand.from_dataframe(nonnull, threshold=50_000)
```

**Comment by iboates** [comment]
Oh, I thought for sure that I had all the null geometries gone. My mistake.

**Comment by ljwolf** [comment]
No problem! good luck!

**Comment by iboates** [comment]
Do you think that it is worth making a PR to catch this input case & throw a more descriptive error? Or maybe a `strict` boolean param which would, when `False`, ignore null geometries automatically?
