### ISSUE TITLE
Correct way to compute spatial weights in libpysal

### ISSUE THREAD

**Issue by vaclavkalous** [pysal/libpysal#408]
I am sorry, this is rather a question than an issue, but I have not found what I am looking for in the documentation or anywhere online. My question is the following:

I am running a spatial regression in Python via the libpysal library. To get the spatial weights, my input data in my dataframe look like this (shapely points):

0    POINT (50.03771 14.32943)
1    POINT (50.10815 14.39488)
2    POINT (50.01611 14.53056)
3    POINT (50.07254 14.46753)
4    POINT (50.02791 14.51335)
5    POINT (50.03728 14.34139)
6    POINT (50.04956 14.31686)
7    POINT (50.04254 14.33117)
8    POINT (50.10283 14.5492)
9    POINT (49.96596 14.38119)
And the code to get the weights:

`knn_spatial = libpysal.weights.KNN.from_dataframe(df,geom_col = 'new_geo', k = 3)

band_spatial = libpysal.weights.DistanceBand.from_dataframe(df,geom_col = 'new_geo',
                                                            threshold = 0.0005)`

I am now wondering if this approach is correct, as my input points are not in cartesian system but they are geographical coordinates. Is this a valid way to compute the distance weight matrix, or do I need to convert the GPS to the cartesian coordinates? 
Many thanks!

**Comment by sjsrey** [comment]
Have a look at the [weights chapter](https://geographicdata.science/book/notebooks/04_spatial_weights.html) of a forthcoming book on PySAL. The [section on great circle distances](https://geographicdata.science/book/notebooks/04_spatial_weights.html#great-circle-distances) may be helpful for your case.

**Comment by vaclavkalous** [comment]
@sjsrey Thank you, that helps a lot! :)
