### ISSUE TITLE
notebooks links in tutorials broken

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#417]
It appears the some behavior in `Jinja`/`nbsphinx` has changed and now the links that are included at the top of tutorials don't work to send back to the original notebook ("This page was generated from `notebooks/xxxx.ipynb`"). This is affecting all submodules that rebuilt docs recently (libpysal, spaghetti, spopt, esda). To see that is was previously successful, see [spreg](https://pysal.org/spreg/notebooks/GM_Lag_example.html), which docs haven't been rebuild recently. The problem seems to be in the [`set docname`](https://github.com/pysal/libpysal/blob/ed19d4f3151201cd1cf8fcfa423c2b7837fea56f/docs/conf.py#L294) statement within `nbsphinx_prolog`, but I haven't been able to figure out how to correct the bad link generation. 

An example:
* previously generated:
  * https://github.com/pysal/spopt/blob/main/notebooks/reg-k-means.ipynb
* currently generated:
  * https://github.com/pysal/spopt//home/runner/work/spopt/spopt/docs/notebooks/reg-k-means.ipynb

**Comment by martinfleis** [comment]
GeoPandas uses

```
__ https://github.com/geopandas/geopandas/blob/master/doc/source/{{ docname }}
```
instead of 

```
__ https://github.com/pysal/libpysal/{{ fullpath }}
```

used here. I'd follow its model since it seems to work on today's builds correctly.

**Comment by jGaboardi** [comment]
@martinfleis Eureka! Great solution! Got it working [for `spopt`](https://pysal.org/spopt/notebooks/reg-k-means.html).
