### ISSUE TITLE
ShapelyDeprecationWarning for asShape in cg/shapely_ext and weights/_contW_lists

### ISSUE THREAD

**Issue by data-wombat** [pysal/libpysal#440]
With the recent update to Shapely 1.8.0, a lot of warnings are appearing for the upcoming Shapely 2.0 deprecation.

For command `wq =  libpysal.weights.Queen.from_dataframe(uk_proj)` where `uk_proj` is just a UK borders [geojson](https://opendata.arcgis.com/datasets/01fd6b2d7600446d8af768005992f76a_2.geojson) read into a GeoDataFrame, the following error appears:

> /usr/local/lib/python3.7/dist-packages/libpysal/weights/_contW_lists.py:31: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
> return list(it.chain(*(_get_boundary_points(part.boundary) for part in shape)))

For commands `poly_window = shapely_ext.unary_union(simple_poly.geometry)` where `simple_poly` is a simplified and decluttered Multipolygon of the above UK geojson, error output is:

> /usr/local/lib/python3.7/dist-packages/libpysal/cg/shapely_ext.py:222: ShapelyDeprecationWarning: The proxy geometries (through the 'asShape()', 'asMultiPolygon()' or 'MultiPolygonAdapter()' constructors) are deprecated and will be removed in Shapely 2.0. Use the 'shape()' function or the standard 'MultiPolygon()' constructor instead.
>   o.append(geom.asShape(shape))
> Exception ignored in: <function BaseGeometry.__del__ at 0x7f04e5754560>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/shapely/geometry/base.py", line 209, in __del__
>     self._empty(val=None)
>   File "/usr/local/lib/python3.7/dist-packages/shapely/geometry/base.py", line 199, in _empty
>     self._is_empty = True
>   File "/usr/local/lib/python3.7/dist-packages/shapely/geometry/proxy.py", line 44, in __setattr__
>     object.__setattr__(self, name, value)
> AttributeError: can't set attribute

I don't know how to do a comprehensive search for all the ShapelyDeprecationWarnings affecting libpysal, but these are what turned up in my work this week, and I'd be grateful to know if they could be updated before Shapely2.0.

Thank you for a beautiful library.

- Platform information: **Google Colab**, command output:
posix linux
posix.uname_result(sysname='Linux', nodename='8793a06d03fd', release='5.4.104+', version='#1 SMP Sat Jun 5 09:50:34 PDT 2021', machine='x86_64')

- Python version:  3.7.12 (default, Sep 10 2021, 00:21:48) 

- SciPy version: 1.4.1

- NumPy version: 1.19.5

**Comment by martinfleis** [comment]
I think that those should all be resolved now. I tried to clear them in #437. You can try installing a master version from GitHub to get rid of them.
