### ISSUE TITLE
Does release GHA work?

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#444]
I am not sure if the recent release GHA workflow is able to upload to PyPI. See the archive and compare to GitHub releases - https://pypi.org/project/libpysal/#history. 

cc @jGaboardi

**Comment by jGaboardi** [comment]
hmmm. Not able to see the diagnostic from [the last time this was run](https://github.com/pysal/libpysal/runs/2926315274?check_suite_focus=true), but both the latest [GitHub (`v4.5.1.post2`)](https://github.com/pysal/libpysal/releases/tag/v4.5.1.post2) and PyPI [`v4.5.1`](https://pypi.org/project/libpysal/4.5.1/) releases were done on 2021/06/27. So it appears that the GHA ran properly for the `v4.5.1` release and then simply wasn't run.

Maybe for now we should simply push up the `v4.5.1.post2` release to PyPI manually, but we should also consider [updating the workflow](https://github.com/pysal/spaghetti/blob/33c4f13ff0a4d4339b555852f486e8ae23d77d0d/.github/workflows/release_and_publish.yml#L40-L54) and adding a [manual trigger](https://github.com/pysal/spaghetti/blob/33c4f13ff0a4d4339b555852f486e8ae23d77d0d/.github/workflows/release_and_publish.yml#L13-L18).

**Comment by jGaboardi** [comment]
Somewhat related to pysal/momepy#307.

**Comment by martinfleis** [comment]
I think that the `4.5.1` on PyPI is `4.5.1.post2` from here, because there is no other `4.5.1`. It seems that those three releases were attempts to make the GHA work.

**Comment by jGaboardi** [comment]
So does this mean the appropriate tag is not being pushed by the GHA? Or that `v4.5.1.post{1,2}` are being evaluated as older versions than `v4.5.1`?

**Comment by jGaboardi** [comment]
Maybe we should release a `v4.5.2`?

**Comment by martinfleis** [comment]
It seems that the tag is truncated and `.post2` is actually removed before pushing it to PyPI. I just don't know why is that. It doesn't seem to be a versioneer issue.

**Comment by jGaboardi** [comment]
closing since action works again
