### ISSUE TITLE
Shapely Dependancy Added

### ISSUE THREAD

**Issue by schmidtc** [pysal/libpysal#453]
[This commit](https://github.com/pysal/libpysal/commit/cd4b809de38ea0df1c4d2564b72617fcd6f81c4b) adds a dependancy on shapely.

**Comment by martinfleis** [comment]
Ah, that is right. In here https://github.com/pysal/libpysal/commit/cd4b809de38ea0df1c4d2564b72617fcd6f81c4b#diff-1b2654daf0b0d7dae666118222dfd2d588cfe1c833a3908bf069b5b084479d68R1077

That wasn't intentional. I'll issue a fix in a moment. Thanks!
