### ISSUE TITLE
Is 10.yaml missing in ci?

### ISSUE THREAD

**Issue by sjsrey** [pysal/libpysal#458]
https://github.com/pysal/libpysal/blob/8aa08b1c58d6622eddb39885d78c34d75f9d27b6/.github/workflows/build_docs.yml#L23

If I run that workflow manually, it fails. I'm wondering if on other events somehow 10.yaml maps to 310.yaml?

**Comment by knaaptime** [comment]
im pretty sure it should just be 310

**Comment by jGaboardi** [comment]
Yes, this seems to simply be a typo.
