### ISSUE TITLE
address ShapelyDeprecationWarning The 'type' attribute is...

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#487]
We need to address [these warnings](https://github.com/pysal/libpysal/actions/runs/3465557983/jobs/5788432290#step:4:1319) sooner than later:

```
/home/runner/work/libpysal/libpysal/libpysal/weights/_contW_lists.py:23: ShapelyDeprecationWarning: The 'type' attribute is deprecated, and will be removed in the future. You can use the 'geom_type' attribute instead.
    if shape.type.lower() == "polygon":
```

**Comment by martinfleis** [comment]
`geom_type` has been around for a while, so a simple replacement of `.type` with `.geom_type` should do the trick,
