### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jarrodmillman** [pysal/libpysal#489]
Would it be possible to release a new version of libpysal that includes: https://github.com/pysal/libpysal/pull/472

We plan to release NetworkX 3.0 soon (https://github.com/networkx/networkx/milestone/15) and would like to reenable to geospatial gallery examples (https://github.com/networkx/networkx/issues/5840).

**Comment by jGaboardi** [comment]
I am for it.

**Comment by knaaptime** [comment]
cool with me!

**Comment by ljwolf** [comment]
Yeah, I'm fine with a bugfix release, then a larger point release with the additional stuff. I'd be fine with this as 4.6.3 and then the release with the deprecations and weights changes as 4.7

**Comment by sjsrey** [comment]
Sounds good to me. I should be able to start on this tomorrow afternoon.

**Comment by sjsrey** [comment]
4.7.0 is now [released](https://github.com/pysal/libpysal/releases/tag/v4.7.0)

**Comment by sjsrey** [comment]
> > Hi, our plan was to have a minor release by the end of the year with #477 and #484 but given #472 is a fix, we can get a patch release with that one out quickly.
> > @sjsrey @jGaboardi @knaaptime @ljwolf thoughts? We would need to cherry-pick some commits for that but it should be doable.
> 
> #472 was merged, but #477 and #484 have not been merged - I'm not clear what needs to be cherry picked?

@martinfleis can you let me know if this can be closed, or do we need to revisit the cherry picking?

**Comment by martinfleis** [comment]
It is fine.
