### ISSUE TITLE
Import of libpysal causes libpysal examples to download which slows down initialization or completely hangs

### ISSUE THREAD

**Issue by iwishiwasaneagle** [pysal/libpysal#499]
Thank you for filing this issue! To help troubleshoot this issue, please follow
the following directions to the best of your ability before submitting an issue.
Feel free to delete this text once you've filled out the relevant requests. 

Please include the output of the following in your issue submission. If you don't know how to provide the information, commands to get the relevant information from the Python interpreter will follow each bullet point.

Feel free to delete the commands after you've filled out each bullet. 

- Platform information:
```python
>>> import os; print(os.name, os.sys.platform);print(os.uname())
>>> posix.uname_result(sysname='Linux', nodename='*', release='5.15.76-1-MANJARO', version='#1 SMP PREEMPT Sat Oct 29 14:22:16 UTC 2022', machine='x86_64')
```
- Python version: 
```python
>>> import sys; print(sys.version)
>>> 3.10.8 (main, Oct 13 2022, 21:13:48) [GCC 12.2.0]
```
- SciPy version:
```python
>>> import scipy; print(scipy.__version__)
>>> 1.9.3
```
- NumPy version:
```python
>>> import numpy; print(numpy.__version__)
>>> 1.24.0
```

Importing libpysal, such as https://github.com/pysal/momepy/blob/99cf555f3a8c93356c280ccfc5d13111d0518427/momepy/weights.py#L4, will import the whole libpysal library. This includes the examples module https://github.com/pysal/libpysal/blob/284d2ae3d8d2084e6c74901d79cc0e13029c6cce/libpysal/__init__.py#L26, which on import attempts to download some remote datasets https://github.com/pysal/libpysal/blob/284d2ae3d8d2084e6c74901d79cc0e13029c6cce/libpysal/examples/remotes.py#L110 .

This has caused `requests.get` to hang here https://github.com/pysal/libpysal/blob/284d2ae3d8d2084e6c74901d79cc0e13029c6cce/libpysal/examples/remotes.py#L24

Is there a way around this?

I have also opened a issue here https://github.com/pysal/momepy/issues/451

**Comment by sjsrey** [comment]
This has been changed in https://github.com/pysal/libpysal/pull/486 and is available in v4.7.0. The remotes are [no longer downloaded automatically](https://github.com/pysal/libpysal/blob/master/notebooks/examples.ipynb).

**Comment by iwishiwasaneagle** [comment]
Hi @sjsrey , this PR doesn't address this issue though. 

From 
https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/remotes.py#L103-L108
we can see that the datasets are only loaded when the `datasets` property is accessed. So, whilst the remote datasets aren't loaded in https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/remotes.py#L111
they are loaded in https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/__init__.py#L18
Furthermore, the `examples` module is imported in the top-level `__init__.py` here
https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/__init__.py#L26
meaning that all remotes are fetched every time the library is imported.

**Comment by iwishiwasaneagle** [comment]
For anyone else having this issue whilst they're not using the `examples` module, simply comment out line 26.

**Comment by sjsrey** [comment]
> For anyone else having this issue whilst they're not using the `examples` module, simply comment out line 26.

@iwishiwasaneagle can you report your version of libpysal? 

> Hi @sjsrey , this PR doesn't address this issue though.
> 
> From
> 
> https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/remotes.py#L103-L108
> 
> we can see that the datasets are only loaded when the `datasets` property is accessed. So, whilst the remote datasets aren't loaded in
> 
> https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/remotes.py#L111
> 
> they are loaded in
> 
> https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/__init__.py#L18
> 
> Furthermore, the `examples` module is imported in the top-level `__init__.py` here
> 
> https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/__init__.py#L26
> 
> meaning that all remotes are fetched every time the library is imported.

@iwishiwasaneagle can you report `libpysal.__version__`

**Comment by iwishiwasaneagle** [comment]
> > For anyone else having this issue whilst they're not using the `examples` module, simply comment out line 26.
> 
> @iwishiwasaneagle can you report your version of libpysal?
> 
> > Hi @sjsrey , this PR doesn't address this issue though.
> > From
> > https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/remotes.py#L103-L108
> > 
> > we can see that the datasets are only loaded when the `datasets` property is accessed. So, whilst the remote datasets aren't loaded in
> > https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/remotes.py#L111
> > 
> > they are loaded in
> > https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/examples/__init__.py#L18
> > 
> > Furthermore, the `examples` module is imported in the top-level `__init__.py` here
> > https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/__init__.py#L26
> > 
> > meaning that all remotes are fetched every time the library is imported.
> 
> @iwishiwasaneagle can you report `libpysal.__version__`

I'm using v4.7.0, but those links/lines of code above are from the master branch

**Comment by sjsrey** [comment]
@iwishiwasaneagle thanks for reporting back.

4.7.0 does not download the remotes, unless a specific remote is explicitly loaded:

https://github.com/pysal/libpysal/blob/d291e014538f0c8862b70bd0119745aa8c55424a/libpysal/examples/base.py#L242-L253

What does happen is that all remotes are polled for their metadata:
https://github.com/pysal/libpysal/blob/d291e014538f0c8862b70bd0119745aa8c55424a/libpysal/examples/remotes.py#L107

And, I believe you encountered a hung request here:
https://github.com/pysal/libpysal/blob/d291e014538f0c8862b70bd0119745aa8c55424a/libpysal/examples/remotes.py#L22

Is that the issue?

**Comment by sjsrey** [comment]
> Furthermore, the `examples` module is imported in the top-level `__init__.py` here
> 
> https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/__init__.py#L26
> 
> meaning that all remotes are fetched every time the library is imported.

Good point. We should refactor to avoid this.

**Comment by iwishiwasaneagle** [comment]
> @iwishiwasaneagle thanks for reporting back.
> 
> 4.7.0 does not download the remotes, unless a specific remote is explicitly loaded:
> 
> https://github.com/pysal/libpysal/blob/d291e014538f0c8862b70bd0119745aa8c55424a/libpysal/examples/base.py#L242-L253
> 
> What does happen is that all remotes are polled for their metadata:
> 
> https://github.com/pysal/libpysal/blob/d291e014538f0c8862b70bd0119745aa8c55424a/libpysal/examples/remotes.py#L107
> 
> And, I believe you encountered a hung request here:
> 
> https://github.com/pysal/libpysal/blob/d291e014538f0c8862b70bd0119745aa8c55424a/libpysal/examples/remotes.py#L22
> 
> Is that the issue?

Yes, I believe it is.

> > Furthermore, the `examples` module is imported in the top-level `__init__.py` here
> > https://github.com/pysal/libpysal/blob/f7a5c957480a7b78634632b86d0666e7d60436fd/libpysal/__init__.py#L26
> > 
> > meaning that all remotes are fetched every time the library is imported.
> 
> Good point. We should refactor to avoid this.

I believe this is probably the best solution.

Happy to have a look at this myself after NYE. Currently replying from mobile.
