### ISSUE TITLE
Change default branch from `master` to `main`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#517]
Change default branch from `master` to `main`. For more info see pysal/libpysal#353.

**Comment by martinfleis** [comment]
It seems that someone did something regarding master and main here but not properly. As a result, we have both, main is a default but all the PRs still point to master. And the one I just merged was merge to master, not main... @jGaboardi do you have the proper rights to look into that here? We need to ensure that master is no longer present and that PRs are properly targeted. GH has a functionality to do that all automatically but not sure if it is not too late now with main as default.

**Comment by jGaboardi** [comment]
After (an inexhaustible) review of the commit history I am not sure exactly what happened but IIRC that `main` branch was added before the fancy GitHub switching tool existed.

**Comment by jGaboardi** [comment]
I have the rights as admin, but not full rights. @sjsrey Can we get @martinfleis granted the full permissions here?

**Comment by martinfleis** [comment]
The main should be up to date now, so master can be probably removed? But that may not be possible since all the PRs target it. Not sure what the best way forward is at this point, never got to this situation.

**Comment by jGaboardi** [comment]
ugh...

**Comment by sjsrey** [comment]
> I have the rights as admin, but not full rights. @sjsrey Can we get @martinfleis granted the full permissions here?

Admin rights is the top level I can give? I gave it to @martinfleis as well.

**Comment by jGaboardi** [comment]
@martinfleis, like you said, the default branch in `pysal/libpysal` is `main`, but your remote (`martinfleis/libpysal`) is still `master`. So when you do a `git push origin <branch>` doesn't your remote default take precedent and create a PR from that branch (`master`)?

**Comment by martinfleis** [comment]
I have manually retargeted all open PRs and removed master.

## For contributors

The GitHub interface will typically explain what you need to do as contributor to a project that changed the default name, but putting it here as well (copying the instructions from dask https://github.com/dask/dask/issues/7199).

### What you'll see

Once the name on github is changed, when you try to `git pull` you'll get

```shell
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
```

### What you need to do

First: **head to your fork and rename the default branch there** Then:

```shell
git branch -m master main
git fetch origin
git branch -u origin/main main
```
