### ISSUE TITLE
W.plot() raises TypeError due to indexing a GeoDataFrame with a dict

### ISSUE THREAD

**Issue by obisargoni** [pysal/libpysal#525]
Exception raised when working through the spatial weights tutorial: https://pysal.org/libpysal/notebooks/weights.html

Reproducing the issue:
```
import libpysal
import matplotlib.pyplot as plt

from libpysal.weights import Queen, Rook, KNN
import geopandas
pth = libpysal.examples.get_path("mexicojoin.shp")
gdf = geopandas.read_file(pth)

w_rook = Rook.from_dataframe(gdf)
ax = gdf.plot(edgecolor='grey', facecolor='w')
f,ax = w_rook.plot(gdf, ax=ax,
        edge_kws=dict(color='r', linestyle=':', linewidth=1),
        node_kws=dict(marker=''))
```

Throws:
```
TypeError: Passing a dict as an indexer is not supported. Use a list instead.
```

- Platform information:
```
posix linux
posix.uname_result(sysname='Linux', nodename='XXX', release='5.19.0-41-generic', version='#42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2', machine='x86_64')
```
- Python version: 
```
3.10.10 (main, Mar 14 2023, 16:03:24) [GCC 11.3.0]
```
- SciPy version:
```
1.10.1
```
- NumPy version:
```
1.24.3
```

- Geopandas version:
```
0.13.0
```

- Pandas version
```
2.0.1
```

- Libpysal version
```
4.7.0
```

**Comment by obisargoni** [comment]
Fix I have made locally is to change line 1290 of libpysal/weights/weights.py from:
```
for idx, neighbors in self:
```
to:
```
for idx, neighbors in self.neighbors.items():
```

**Comment by sjsrey** [comment]
> A fix I have made locally is to change line 1290 of libpysal/weights/weights.py from:
> 
> ```
> for idx, neighbors in self:
> ```
> 
> to:
> 
> ```
> for idx, neighbors in self.neighbors.items():
> ```

Thanks for reporting this. The relevant line in main is now [1476](https://github.com/pysal/libpysal/blob/main/libpysal/weights/weights.py#L1476).

@ljwolf should we implement this change or is there another fix you may have in mind?

**Comment by martinfleis** [comment]
We wanted to refactor this and merge the implementation with the one we have in splot. Though this seems to be a tiny fix, so I suggest we go ahead and fix this now. The refactoring would probably be part of weights refactoring anyway, to build it on top of new data structure.

**Comment by jacobpascalcoblentz** [comment]
+1 to this. known error. fixed?

**Comment by martinfleis** [comment]
Not yet but it at least the minimal bug fix should make it to the next one coming within next two weeks.
