### ISSUE TITLE
is `geomet` still a dependency?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#530]
* if so, `geomet` is now available [via `conda-forge`](https://anaconda.org/conda-forge/geomet) and it can be moved from [`requirements_plus_pip.txt`](https://github.com/pysal/libpysal/blob/main/requirements_plus_pip.txt) to [`requirements_plus_conda.txt `](https://github.com/pysal/libpysal/blob/main/requirements_plus_conda.txt)
* if not, `requirements_plus_pip.txt` can be entirely removed anyway
* testing suite passes without `geomet`

**Comment by martinfleis** [comment]
I only found this https://github.com/pysal/libpysal/blob/8fa39a8c919f2629f4439254343670e691047f42/libpysal/io/iohandlers/db.py#L6-L9

which also indicates clearly how to replace it :)

**Comment by jGaboardi** [comment]
Closed via https://github.com/pysal/libpysal/pull/579

**Comment by QuLogic** [comment]
It's no longer in the requirements, or tested AFAICT, but the `try` is still in the file linked above. Should that be removed now, since it's untested?

**Comment by martinfleis** [comment]
The whole `db.py` should be deprecated and removed.
