### ISSUE TITLE
`sqlalchemy` and `geomet`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#588]
Both `sqlalchemy` and `geomet` were removed from requirements in #579, `sqlalchemy` by accident and `geomet` on purpose.

* For `sqlalchemy` we simply need to add that back into `pyproject.toml` and in the appropriate `ci/*` environment.
* For `geomet` it's a bit more complicated since we need to address some functionality and testing:
  * [libpysal/io/iohandlers/db.py](https://github.com/pysal/libpysal/blob/0ea928aaecd95343a32900acfc23dfb8a49d5fd6/libpysal/io/iohandlers/db.py#L7)
  * [libpysal/io/iohandlers/\_\_init\_\_.py](https://github.com/pysal/libpysal/blob/0ea928aaecd95343a32900acfc23dfb8a49d5fd6/libpysal/io/iohandlers/__init__.py#L22)
  * [libpysal/io/iohandlers/tests/test_db.py](https://github.com/pysal/libpysal/blob/0ea928aaecd95343a32900acfc23dfb8a49d5fd6/libpysal/io/iohandlers/tests/test_db.py#L17)

**Comment by jGaboardi** [comment]
@martinfleis  I think this whole block below can go, no? `shapley` is now a hard dependency and `geomet` is gone.


https://github.com/pysal/libpysal/blob/0ea928aaecd95343a32900acfc23dfb8a49d5fd6/libpysal/io/iohandlers/db.py#L5-L13

**Comment by martinfleis** [comment]
Yes, we should use shapely by default.

**Comment by jGaboardi** [comment]
The [`Test_sqlite_reader`](https://github.com/pysal/libpysal/blob/5d09bc6a27d371dba2c5dbad56535f2987406bbe/libpysal/io/iohandlers/tests/test_db.py#L36C7-L36C25) test is causing trouble due to [this helper fucntion](https://github.com/pysal/libpysal/blob/5d09bc6a27d371dba2c5dbad56535f2987406bbe/libpysal/io/iohandlers/tests/test_db.py#L27C35-L27C35). Going to refactor the test to ensure passing.
