### ISSUE TITLE
get rid of `test_NameSpace.py`?

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#596]
As far as I can tell, [`test_NameSpace.py`](https://github.com/pysal/libpysal/blob/main/libpysal/test_NameSpace.py) is no longer used and is from pre-libpysal days. Should we get rid of it?

cc @sjsrey @knaaptime @martinfleis

**Comment by martinfleis** [comment]
Yup, it looks like it is some relict from 2018 :)
