### ISSUE TITLE
allow ids in graph when passing sparse

### ISSUE THREAD

**Issue by knaaptime** [pysal/libpysal#626]
following the discussion in the dev meeting 11/2/23 we will allow an `ids` argument when a sparse array is used to instantiate a `Graph` object (using either `build_` or `from_`), but **only** for sparse objects

**Comment by martinfleis** [comment]
-> https://github.com/pysal/libpysal/issues/562#issuecomment-1791096379

not sure what is the best way forward for graph stuff, if one issue or separate issues

**Comment by knaaptime** [comment]
i saw that comment go up during the meeting, but i only added this one here to remind myself cause ive started forgetting about that list now that most of it is in place

**Comment by martinfleis** [comment]
Yeah, I think it makes sense to have an issue per task at this point.

**Comment by jGaboardi** [comment]
xref #562
