### ISSUE TITLE
Patch v4.8.0 with #583

### ISSUE THREAD

**Issue by ambarrio** [pysal/libpysal#656]
Dear authors,

Would it be possible to release a patched 4.8.0 with the #583 on top of it? This would facilitate very much its usage in our program, [pixelator](https://github.com/PixelgenTechnologies/pixelator), as we would be able to keep supporting python 3.8 and 3.9.

Also, it will help packaging libpysal in container images (Singularity).

**Comment by martinfleis** [comment]
We usually don't do that but I suppose we could make an exception and patch older minor version. This should be easy to backport. 

Let's wait for the others but I can eventually do that in coming days or early next week.

**Comment by martinfleis** [comment]
@knaaptime @jGaboardi @sjsrey any objections to this?

**Comment by jGaboardi** [comment]
I have no objections at all. My one stipulation is that we do a `v4.8.0rc1`, see that through to release on `conda-forge`, and then wait at least 1 day to see about downstream failures. Very much like to avoid what happened several weeks ago.

**Comment by knaaptime** [comment]
Fine with me

**Comment by sjsrey** [comment]
Good by me. But we should be clear that this is not something that can always be accommodated - if someone has the bandwidth then we will do it, but these requests are competing with a large set of demands.

**Comment by ambarrio** [comment]
Thanks a lot everyone for your quick help on this. It is really great to see that actions like this enable other projects using pysal.

**Comment by martinfleis** [comment]
@ambarrio can you test against https://pypi.org/project/libpysal/4.8.1rc1/? I will cut the proper release if it works.

@jGaboardi I don't think conda-forge will pick up a pre-release. It is against their policy to publish pre-releases on conda-forge.

> wait at least 1 day to see about downstream failures

We won't see them. Most people will get 4.9.2, not 4.8.1 anyway. If @ambarrio can check their use cases, I think we can go ahead and cut the full thing. I also don't want to spend more time than needed on this.

**Comment by ambarrio** [comment]
@martinfleis this works fine on our side. Thanks a ton!

**Comment by martinfleis** [comment]
Cool. I'll cut a proper 4.8.1 then. Thanks for checking.

**Comment by martinfleis** [comment]
Done. I am not sure if it will propagate to conda-forge as it is an older version than the most recent one there but at least you have PyPI to get it there. We have no compiled components so it should be no issue.
