### ISSUE TITLE
Build Graph from H3

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#667]
I have an implementation of building a (higher-order) contiguity Graph based on H3 index. I'd like to expose it as a builder on `Graph, so dumping the code below before I'll forget.

 ```py
import h3

from libpysal import graph

data = ... # dataframe with H3 IDs as an index, like those coming from tobler h3fy
order = 5

neighbors = {}
weights = {}
for ix in data.index:
    rings = h3.hex_range_distances(ix, order)
    for i, ring in enumerate(rings):
        if i == 0:
            neighbors[ix] = []
            weights[ix] = []
        else:
            neighbors[ix].extend(list(ring))
            weights[ix].extend([i] * len(ring))

matrix = graph.Graph.from_dicts(neighbors, weights)
```

It encodes the order as weight now, I was casting to a binary graph and used topological inverse weighting based on that (`inverse = graph.Graph(1 / matrix.adjacency)`). We can figure out what the API should be once the PR is alive?

I also think that the latest beta release of h3 completely changed the API so the h3 calls will need to change a bit but it's been beta for a year. 

based on https://github.com/Urban-Analytics-Technology-Platform/demoland-project/blob/main/code/04_generalisation/create_spatial_weights.ipynb

**Comment by ljwolf** [comment]
It would be interesting to try to generalise this for many of [the common hierarchical indices...](https://github.com/allixender/dggrid4py)

**Comment by knaaptime** [comment]
>I also think that the latest beta release of h3 completely changed the API so the h3 calls will need to change a bit but it's been beta for a year.

you think that's related to [these failures](https://github.com/pysal/tobler/actions/runs/7216611757/job/19663099686) somehow? not sure what would've changed

**Comment by martinfleis** [comment]
@knaaptime no, the version of h3 has not changed in those test envs. neither did GEOS. not sure where that comes from.
