### ISSUE TITLE
Interest in Graph.apply?

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#675]
Within `momepy`, I often need to apply a custom function over an array of values or geometries of neighbours to any focal. I think that a function like `apply` shown below would go a long way in there. Shall we add it to Graph in this form? Or using different name?

```py
def apply(graph, y, func, **kwargs):
    grouper = y.take(
        graph.adjacency.index.codes[1]
        ).groupby(graph.adjacency.index.codes[0])
    result = grouper.agg(func, **kwargs)
    result.index = graph.unique_ids
    return result
```

This allows customised lags like getting median or mode or if ´y´is a GeoSeries apply a geo `func`.

```py
# median
apply(queen, df.area, np.median)

# IQR
apply(queen, df.area, scipy.stats.iqr)

# area of convex hull around neighbors
apply(queen, df.geometry, lambda x: x.unary_union.area)
```

_I love how simple this is on top of Graph_

**Comment by ljwolf** [comment]
Definitely want to implement this and support it for users. 

We can write some "faster" usual reductions (lag_spatial/lag_categorical), and then provide apply() as a more general way of applying a reduction across the neighbor sets
