### ISSUE TITLE
fix README for pypi

### ISSUE THREAD

**Issue by sjsrey** [pysal/libpysal#7]
pypi evidently prefers rst: https://pypi.python.org/pypi/libpysal/3.0.0

also the readme we have is referring to pysal_core, so `s/pysal_core/libpysal/` is required

**Comment by ljwolf** [comment]
I think pypi can use `markdown` now.

**Comment by jGaboardi** [comment]
This is now resolved [`libpysal` in PyPi](https://pypi.org/project/libpysal/)
