### ISSUE TITLE
Migration guide W->Graph

### ISSUE THREAD

**Issue by sjsrey** [pysal/libpysal#712]
Two teaching materials where one is derived from the other and updated to use Graph instead of W.

- Dani's W - https://darribas.org/gds_course/content/bE/lab_E.html
- Martin's Graph https://martinfleischmann.net/sds/chapter_04/hands_on.html

Apart from the different datasets, it is nearly 1:1 and can be used as a basis of the migration guide.

_edited by @martinfleis_

**Comment by knaaptime** [comment]
following the discussion from the [June dev meeting](https://github.com/orgs/pysal/discussions/1278), we want to open a discussion about Graph nomenclature (specifically when you need to work with multiple graphs simultaneously e.g. from libpysal and networkx at once) it might be easier to rename `Graph` to `GeoGraph` or similar. Opening here for discussion so we can vote in the next dev meeting

**Comment by martinfleis** [comment]
I am tentatively for the renaming as it is going to be clearer to the user what is required where and avoids some confusion between different graph representations. But I also don't feel super strongly about this. It's also going to break some of my research code and teaching materials but I can deal with that easily.

**Comment by jGaboardi** [comment]
xref: https://github.com/pysal/momepy/issues/579

I have no strong opinions either way, so probably not a bad to go with the more distinctive `GeoGraph`. Wasn't `GeoGraph` the original name that was under consideration when the refactor first started out?

**Comment by martinfleis** [comment]
Existence of this https://geograph.readthedocs.io/en/latest/ may affect the decision here...

**Comment by jGaboardi** [comment]
Are there any other alternative names being thrown around?

**Comment by knaaptime** [comment]
at the steering committee meeting this morning we voted to keep `Graph` for the time being

**Comment by jGaboardi** [comment]
complete via #733
