### ISSUE TITLE
Centroid or representative point in graph plotting

### ISSUE THREAD

**Issue by martinfleis** [pysal/libpysal#735]
Right now, when plotting graphs, we get node location using centroid. Occasionally, this means, that the node ends outside of the polygon, which can make graph interoperation a bit cumbersome. One example below but that one is easy. I can image, for example, some of the gerrymandered polygons causing a bit more of a trouble.

Shall we switch to using representative points instead? It is a bit slower but in this case it matters sometimes.

<img width="414" alt="Screenshot 2024-07-01 at 21 31 24" src="https://github.com/pysal/libpysal/assets/36797143/b5c4fbd7-8e37-42a3-b2b3-668725765ebd">

**Comment by jGaboardi** [comment]
Perhaps a default keyword to "representative_point" so that we can still get centroids if desired?

**Comment by martinfleis** [comment]
If desired, you can do `queen.explore(gdf.centroid)`. I'd rather avoid adding keywords.
