### ISSUE TITLE
need to cut `libpysal==v4.12.0`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#748]
We need to cut a `libpysal==v4.12.0` to ensure `esda` functionality when installing via `conda-forge` and `pip`.

xref:
* #723 
* https://github.com/pysal/esda/issues/319#issuecomment-2218824614
* https://github.com/pysal/esda/issues/299

**Comment by martinfleis** [comment]
Can we wait a few days to get the open PRs in? There may also be some other changes based on the use case in esda when I get to the other classes there.

**Comment by jGaboardi** [comment]
xref:
* https://github.com/pysal/esda/pull/296
* https://github.com/pysal/esda/pull/295
* https://github.com/pysal/esda/pull/293

**Comment by martinfleis** [comment]
Yes

**Comment by jGaboardi** [comment]
https://github.com/pysal/esda/pull/296#issuecomment-2231798831

**Comment by martinfleis** [comment]
I would still do https://github.com/pysal/libpysal/pull/733 and one more (will push in a sec) to move Graph out of experimental.

**Comment by jGaboardi** [comment]
xref #754

**Comment by jGaboardi** [comment]
complete -- https://github.com/pysal/libpysal/releases/tag/v4.12.0
