### ISSUE TITLE
Nightli.es build permissions

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#77]
For some reason I have permission to set `Nightli.es` builds for both `spint` and `spglm`, but not for the actual package I maintain, `spaghetti`. Is there an quick solution for this? I haven't found one. The screen shot below was taken from [pysal's travis profile](https://travis-ci.org/profile/pysal).

![nightli](https://user-images.githubusercontent.com/8590583/42767989-f5915360-88e3-11e8-87b8-ba4c5effc789.png)

**Comment by sjsrey** [comment]
@jGaboardi I just bumped up you permissions on the pysal/spaghetti settings to Admin. Can you check if this fixes your access permissions on Nightli.es?

**Comment by jGaboardi** [comment]
@sjsrey permissions just kicked in. Thanks!
