### ISSUE TITLE
ENH: shared perimeter contiguity weighting. 

### ISSUE THREAD

**Issue by ljwolf** [pysal/libpysal#80]
When we're coming from geodataframes, we can probably implement a shared perimeter weighting scheme pretty easily. This means that, instead of contiguity being a binary relation, we'd assign the weight to the adjacency graph according to how much of the polygon's perimeter is shared along their shared edge. 

For Queen weights, this would necessarily reduce them down to Rook weights, so we would implement this only for Rook. 

0. do a first pass for binary contiguity
1. for neighbors:
    1. `poly_focal.intersection(poly_neighbor).length / poly_focal.boundary.length` would give the asymmetric perimeter weight
    2. `poly_focal.intersection(poly_neighbor).length / (poly_focal.boundary.length + poly_neighbor.length)` would give a symmetrized perimeter weight

This would be an interesting addition to the library. It could be implemented as a function in `util`, and then applied at the end of initialisation for `Rook.from_shapefile` or `from_dataframe` if `perimeter=True`.

**Comment by knaaptime** [comment]
this would also provide for proportional voting in `lag_categorical`

**Comment by knaaptime** [comment]
do distance-based weights follow the same logic for area or do they just use centroids?

**Comment by knaaptime** [comment]
we have this because @ljwolf added [this code](https://github.com/pysal/segregation/blob/090be5ec7431b53b84e788d4d60804245323fb7e/segregation/spatial/spatial_indexes.py#L113) to segregation, so should we go ahead and move it here?

**Comment by ljwolf** [comment]
@knaaptime any updates on this? I'd say yes.

**Comment by knaaptime** [comment]
imo it would be better to move it here and import into segregation so I'm happy to do that. Are we going to keep the `Capital_Underscore` convention or should I do `lowercase_underscore` with an eye toward adopting [pep8 naming conventions](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names) in the future?

**Comment by ljwolf** [comment]
Hi @knaaptime, this is implemented in Segregation, correct? That implementation needs to be kicked up here, not remain in segregation.

**Comment by knaaptime** [comment]
xref #507
