### ISSUE TITLE
libpysal/libpysal/cg/__init__.py not importing `rtree`

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#90]
- Platform information:
`posix darwin`
- Python version: 
`3.6.6`
- SciPy version:
`1.1.0`
- NumPy version:
`1.15.0`

`rtree` is currently not being imported during `__init__` (though it is being deleted), causing failures in `spaghetti.utils.py`.

```python
from .shapes import *
from .standalone import *
from .locators import *
from .kdtree import *
from .sphere import *
from .voronoi import *
from .alpha_shapes import alpha_shape, alpha_shape_auto

del rtree
del kdtree
del locators
del voronoi
del standalone
del alpha_shapes
del shapes
```

**Comment by ljwolf** [comment]
yes, see #89 and also [minutes from the call today](https://hackmd.io/uTHURhfCTNm_BHg6-uSbWA), point 2, second bullet. 

I was eager to clean up the api, and made a change that breaks things in weird ways I didn't anticipate.

**Comment by jGaboardi** [comment]
Ah, OK. I have a PR ready to submit that simply includes the `from .rtree import  *` if you would like.

**Comment by ljwolf** [comment]
sure!
