### ISSUE TITLE
weights.Voronoi is a function, not a class. 

### ISSUE THREAD

**Issue by ljwolf** [pysal/libpysal#99]
[This thread](https://github.com/pysal/libpysal/pull/98/files/34a898821a6be25edf54366f07884534d6032209#r210394634) discusses this rough edge. 

Whether or not we should document for the 2.0 release, then change (mandating another subsequent change to the documentation) or change (attempting to avoid spalling out into the rest of the library), then document the 2.0 release is up for grabs.

**Comment by jGaboardi** [comment]
#135
